### ISSUE TITLE
Doc ;-)

### ISSUE THREAD

**Issue by mhicauber** [bablukid/cagette#1]
Bonjour

Une petite doc d'install est-elle disponible quelque part ? 
Merci d'avance.

**Comment by bablukid** [comment]
Bonjour,
Malheureusement le projet est encore jeune et il n'y a pas encore de doc d'install !

Pour l'instant Cagette fonctionne uniquement pour Neko ( un interpreteur de script similaire à PHP mais beaucoup plus rapide ) ce qui nécéssite d'installer Neko et mod_neko pour le couplage avec Apache. http://aide.cagette.net/doku.php?id=install_neko

Il faut que je prenne du temps pour paufiner une version déjà compilée pour PHP qui serait beaucoup facile à installer sur une stack LAMP classique.

**Comment by mhicauber** [comment]
Ok - super initiative par ailleurs, vais tester l'appli rapido pour la proposer à mon AMAP (qui souffre du syndrome contrat en 3 exemplaires...). Merci !

**Comment by bablukid** [comment]
Bonjour @mhicauber , j'ai enfin fait une doc d'installation pour Ubuntu : http://aide.cagette.net/doku.php?id=install_neko

Sinon tu peux tester directement en ligne en cliquant sur "Essayer" sur www.cagette.net

**Comment by mhicauber** [comment]
super merci ! je teste ça rapidement.
