### ISSUE TITLE
Accès rapide aux commandes en cours pour les coordinateurs

### ISSUE THREAD

**Issue by yohanboniface** [bablukid/cagette#101]
Bonjour,

J'ai pas trouvé mieux que 4 clics pour arriver à une page de commandes, type https://app.cagette.net/contractAdmin/orders/4096?d=194349

J'ai peut-être raté quelque chose, sinon serait-il possible d'ajouter un module "commandes actives" sur la page d'accueil des coordinateurs?

Merci!

Yohan

**Comment by bablukid** [comment]
C'est prévu , mais notre todolist fait 84 kms donc ... faut etre patient
