### ISSUE TITLE
Nouvelle commande par un coordinateur: masquer les produits non disponibles

### ISSUE THREAD

**Issue by yohanboniface** [bablukid/cagette#106]
Bonsoir,

Serait-il possible de masquer les produits non disponibles dans la page nouvelle commande ?

Voir par exemple:

![screenshot from 2018-12-28 22-50-51](https://user-images.githubusercontent.com/146023/50529178-558ac800-0af3-11e9-8700-184bbb871bef.png)

Merci! :)

**Comment by bablukid** [comment]
Hello,
Pour les suggestions, utilise plutot cette page : https://cagette.uservoice.com/forums/276610-general/filters/top

merci !
