### ISSUE TITLE
Stockage du mot de passe

### ISSUE THREAD

**Issue by darakt** [bablukid/cagette#107]
#24 
Je viens de changer mon mot de passe et de le recevoir en clair..., l'issue est donc toujours d'actualité
D'autre part comment le stockez vous?

**Comment by esprit-libre** [comment]
Idem, ça m'a fait bondir. Un changement est prévu pour ne stocker que le hash md5 (ou autre algo) ?

**Comment by bablukid** [comment]
C'est bien le cas, le pass est hashé en MD5 + clé secrete, puis enregistré.

Le mot de passe est envoyé par mail uniquement au moment ou la personne valide le formulaire... je ne le garde jamais en clair ensuite.

Ce mail est utile car beaucoup d'utilisateurs de Cagette ne sont pas très doués et on besoin de ce rappel.  Pour des utilisateurs avertis comme vous, vous pourrez effacer tout de suite le mail et il ne restera aucune trace de votre pass en clair.
