### ISSUE TITLE
Impossible de gérer les cotisations des adhérents (version PHP)

### ISSUE THREAD

**Issue by orsonfrut** [bablukid/cagette#11]
Lorsque l'on clique sur "Gérer les cotisations" sur un utilisateur on obtient le message suivant:

Parse error: syntax error, unexpected '$ctx' (T_VARIABLE), expecting ')' in /home/amapomme/lang/fr/tmp/membership__default.mtt.php on line 29

**Comment by bablukid** [comment]
ok merci, ça sera corrigé pour la version 0.9.1
http://www.cagette.net/wiki/changelog
