### ISSUE TITLE
erreur suite mise à jour version Naxo

### ISSUE THREAD

**Issue by akakeronos** [bablukid/cagette#110]
Suite à la mise à jour de notre instance la page contract ne fonctionne plus
L'erreur affichée est "Missing config attribute : 'langnames'"

Le log est 

Called from sugoi/Config.hx line 55
Called from controller/Contract.hx line 34
Called from a C function
Called from C:\HaxeToolkit\haxe\std/haxe/web/Dispatch.hx line 132
Called from C:\HaxeToolkit\haxe\std/haxe/web/Dispatch.hx line 131
Called from controller/Main.hx line 336
Called from a C function
Called from C:\HaxeToolkit\haxe\std/haxe/web/Dispatch.hx line 132
Called from C:\HaxeToolkit\haxe\std/haxe/web/Dispatch.hx line 131
Called from sugoi/BaseApp.hx line 226
Called from sugoi/BaseApp.hx line 216
Called from a C function
Called from App.hx line 49
Called from sugoi/BaseApp.hx line 379
Called from sys/db/Transaction.hx line 32

**Comment by bablukid** [comment]
Il faut que tu regardes ton ancien config.xml et que tu récupères tous les paramètres.

le fichier d'exemple est https://github.com/bablukid/cagette/blob/master/config.xml.dist

**Comment by bablukid** [comment]
L'erreur est qu'il manque la ligne langnames dans config.xml 
( langnames="Français;Deutsch;English" )
