### ISSUE TITLE
erreur lors du chargement d'une illustration d'un producteur

### ISSUE THREAD

**Issue by akakeronos** [bablukid/cagette#111]
Suite à la mise à jour avec l'archive disponible au téléchargement depuis la page dev:update du wiki 

passage de 
0.9.2-Ca51eb4d+2017.9.1.18.7-Neko
à 
0.9.2-C09ac9d8+2018.3.26.13.25-Neko 

Lors de l'ajout d'un fichier jpg pour illustrer une fiche de producteur j'ai eu une erreur 
Process creation failure : convert

log: 
Called from C:\HaxeToolkit\haxe\std/neko/_std/sys/io/Process.hx line 99
Called from a C function
Called from C:\HaxeToolkit\haxe\std/neko/_std/sys/io/Process.hx line 88
Called from sugoi/tools/UploadedImage.hx line 25
Called from controller/Vendor.hx line 106
Called from a C function
Called from C:\HaxeToolkit\haxe\std/haxe/web/Dispatch.hx line 132
Called from C:\HaxeToolkit\haxe\std/haxe/web/Dispatch.hx line 131
Called from controller/Main.hx line 282
Called from a C function
Called from C:\HaxeToolkit\haxe\std/haxe/web/Dispatch.hx line 132
Called from C:\HaxeToolkit\haxe\std/haxe/web/Dispatch.hx line 131
Called from sugoi/BaseApp.hx line 226
Called from sugoi/BaseApp.hx line 216
Called from a C function
Called from App.hx line 49
Called from sugoi/BaseApp.hx line 379
Called from sys/db/Transaction.hx line 32

Est-ce normal que le script cherche un fichier avec un chemin absolu ?

page : /vendor/addImage/9

**Comment by bablukid** [comment]
il cherche à appeler un utilitaire de conversion d'image.

il faut faire "sudo apt-get install imagemagick"
