### ISSUE TITLE
Vendre des cagettes en direct sans passer par un groupe.

### ISSUE THREAD

**Issue by francoiscolas** [bablukid/cagette#113]
Bonjour,
C'est avec joie que je découvre cet outil. Une question, cependant, pourquoi ne pas permettre aux producteurs de vendre directement des "cagettes" sans passer par la création d'un groupe ?

**Comment by bablukid** [comment]
La vente en circuit court n'est rentable que si les achats sont regroupés, sinon le producteur passe trop de temps à faire des livraisons individuelles, et/ou doit ajouter des couts de livraison conséquents à ses produits .... c'est pourquoi nous fonctionnons sur le principe de l'achat groupé, comme le font les AMAP, groupements d'achats associatifs ou d'autres plateformes comme La ruche qui dit oui...  D'autre part, pour faire de la vente sur Internet classique, il existe déjà une multitude d'outil pour faire ça.
