### ISSUE TITLE
Installation de Dev : pas de pop-up de login

### ISSUE THREAD

**Issue by Eric86140** [bablukid/cagette#117]
J'ai donc la page d’accueil, avec le logo, les boutons "Connexion" et "Chercher un autre groupe" mais pas la pop up avec "S'identifier"

Est ce que cela aura un rapport avec le fait que dans la version Web,  le code source ligne 48 fait référence à _<script type="text/javascript" src="/js/46/libs.js"></script>_
Tendis que dans la version de développement on a _<script type="text/javascript" src="/js//libs.dev.js"></script>_
Et que le seul fichier approchant dans /js est libs.js et non pas libs.dev.js ?

**Comment by bablukid** [comment]
Hello, ok il te manque libs.dev.js

pull la dernière version sur github, et exécute "npm run libs:dev" , ça va le générer.

Sinon tu peux éventuellement copier libs.js et le renommer en libs.dev.js si tu ne prévois pas de faire du dev JS

**Comment by Eric86140** [comment]
Ce problème est corrigé
