### ISSUE TITLE
Installation de dev : problème d'identification

### ISSUE THREAD

**Issue by Eric86140** [bablukid/cagette#118]
UPDATE Session SET lastTime = '2019-10-02 01:23:34', uid = 1 WHERE sid = 'oc5fFijOXfdynIkX7Pxt3CkORiZw7wjV' Duplicate entry '1' for key 'Session_uid'
Est l'erreur lorsque j'essaye d'identifier un user dans la base. Visiblement il y a des erreurs de données dans la base. De mémoire il y a vait une documentation sur comment accéder aux bases, mais je ne la retrouve plus.

**Comment by bablukid** [comment]
tu peux accéder à la base en allant sur /db  mais il faut etre loggé avec un compte admin.
Je n'ai jamais eu ce type d'erreur, tu ferais mieux de vider complètement ta base...

**Comment by Eric86140** [comment]
J'ai installé adminer.php pour pouvoir analyser le contenu des bases mysql.
J'ai viré la ligne dans Session qui me posait un problème, et depuis je peut me logguer avec un compte d'administration.
je suis allé dans install pour faire une mise à jour le la base (celle-ci ne peut se faire qu'avec un compte d'aministration). Il me demande une mise à jour à la version 0.12.0-C341ae95+2019.10.1.16.3 .
Effectivement dans Variable, la version est 0.9.2-D2016-11-28-11-19
Malgré le test de la Version (0.9.2), il exécute _0_9_2_dbMigration, et is se plante sur la mise à jour de la table Amap parce que le champ allowedPaymentsType n'existe pas dans la table

Je n'ai pas vu d’exemple comment vérifier l’existence d’un champ, et le créer si nécessaire.
D'un autre coté, le créer par adminer, il faudrait son type ....

**Comment by bablukid** [comment]
il faut vider complétement la base de données, j'ai laissé tomber les migrations, trop compliqué et chronophage

**Comment by Eric86140** [comment]
J'ai installé adminer.php pour pouvoir analyser le contenu des bases mysql.
J'ai viré la ligne dans Session qui me posait un problème, et depuis je peut me logguer avec un compte d'administration.
je suis allé dans install pour faire une mise à jour le la base (celle-ci ne peut se faire qu'avec un compte d'aministration). Il me demande une mise à jour à la version 0.12.0-C341ae95+2019.10.1.16.3 .
Effectivement dans Variable, la version est 0.9.2-D2016-11-28-11-19
Malgré le test de la Version (0.9.2), il exécute _0_9_2_dbMigration, et is se plante sur la mise à jour de la table Amap parce que le champ allowedPaymentsType n'existe pas dans la table

Je n'ai pas vu d’exemple comment vérifier l’existence d’un champ, et le créer si nécessaire.
D'un autre coté, le créer par adminer, il faudrait son type ....

**Comment by Eric86140** [comment]
Finalement j'ai renommé la base pour garder une trace. Et je repars de Zéro.
Je vais surtout m'atteler à garder des fichiers XLS pour pouvoir faire des imports de CSV pour les prochaines fois
