### ISSUE TITLE
Liste d'émargement : nb articles 

### ISSUE THREAD

**Issue by benchti** [bablukid/cagette#12]
Proposition d'ajouter le nb total d'articles sur la liste d'émargement ( ce qui permet de contrôler rapidement dans un colis qu'il y a le bon nombre de produits) . 

http://app.cagette.net/distribution/listByDate/2016-03-26/one

![selection_945](https://cloud.githubusercontent.com/assets/663816/14060772/fa95dcd0-f36e-11e5-886b-3e642c3b6d61.png)

**Comment by bablukid** [comment]
Bonne idée, facile à faire : hop c'est fait !
