### ISSUE TITLE
Imposible to categorize products in a csv file before import

### ISSUE THREAD

**Issue by thedub2001** [bablukid/cagette#120]
Hello,

I need to import products and everything works fine following these steps : 
https://wiki.cagette.net/admin:admin_csvimport

## Problem
 I am not able to categorize products inside this csv file

## Solution
Add a column in the csv file exemple where we fill the kind of product : 
empty for Autres
1 for Fruits & Légumes
2 for Viande et charcuterie
3 for Épicerie
4 for Crèmerie
5 for Boulangerie et pâtisserie
6 for Produits de la mer
7 for Desserts et plats préparés
8 for Boissons

I can begin to look for a solution if someone gives me a small guidance ;)

**Comment by bablukid** [comment]
Hello,
A product is not categorized as "fruits et legumes" but as "potato" , "carrot" ... etc    so it's a very long list.
It's much more easier to categorize the product from the interface, thats why we did'nt import category from CSV

**Comment by thedub2001** [comment]
Sorry but it is NOT easier tu use the interface when you have 50 products
