### ISSUE TITLE
total individualisé par contrat et par adhérent

### ISSUE THREAD

**Issue by akakeronos** [bablukid/cagette#13]
En tant que coordinateur je veux que l'application calcule le montant des sommes dues par un adhérent au contrat afin de pouvoir planifier les paiements et vérifier que les montants payés correspondent bien aux montants dus.
Sur un contrat à commande fixe, après avoir défini les dates de distribution et donc leur nombre ou leur récurrence, je dois voir affiché le coût pour l'adhérent de ses commandes régulières.
Sur un contrat à commande variable, je dois pouvoir afficher le montant total des commandes par adhérents et pas uniquement par livraison ou par produit comme actuellement.
En complément, je dois pouvoir indiquer si l'adhérent règle ses commandes en une ou plusieurs fois et pouvoir indiquer si les différents règlements ont été effectués (un règlement ne correspond pas toujours à une seule livraison)

critère d'acceptation : 
le montant des règlements d'un adhérent s'affiche sur la page contrat du coordinateur et permet à celui-ci de consulter et de gérer les règlements liés aux commandes qu'il a passé pour les adhérents ou que ceux-ci ont passés.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/172413708080950/172746722640581)

**Comment by bablukid** [comment]
La gestion des comptes clients ( solde, historique de paiement, avoirs ...etc ) est prévue pour la prochaine version ( 0.9.2 )

**Comment by datalocale** [comment]
Ok merci
