### ISSUE TITLE
Il manque les informations d'ouverture et de fermeture des commandes sur la page d'accueil utilisateur

### ISSUE THREAD

**Issue by thedub2001** [bablukid/cagette#136]
## Actuellement
En mode utilisateur, on ne voit pas jusque quand on peut passer commande
![01](https://user-images.githubusercontent.com/18016853/68995487-c4e5e380-088e-11ea-9d00-e8d8358625e3.png)

## Comment ça devrait être
En mode administrateur on voit directement depuis et jusque quand la commande est ouverte. Il faudrait simplement rajouter ces informations dans le mode "utilisateur"
![02](https://user-images.githubusercontent.com/18016853/68995500-fced2680-088e-11ea-860b-61d6f9ac578d.png)

**Comment by bablukid** [comment]
La date d'ouverture était déjà affichée ( tant que ce n'est pas ouvert ).

La date de fermeture est affichée depuis lundi
