### ISSUE TITLE
date de début et de fin de contrat individualisées

### ISSUE THREAD

**Issue by akakeronos** [bablukid/cagette#14]
En tant que coordinateur légumes je veux pouvoir gérer un contrat glissant avec des dates de démarrage et de clôture de contrat différentes pour chaque adhérent afin d'éviter de devoir gérer l'ensemble des renouvellement de contrat le même jour.
Le coordinateur définit les dates au niveau de l'adhérent et pas au niveau du contrat et la gestion des règlements est adaptée à ce mode de gestion.

critère d'acceptation : en tant que coordinateur je peux définir une date de démarrage et de clôture pour un contrat annuel par adhérent et le montant à régler s'adapte pour présenter le montant global du par adhérent en fonction des dates de livraisons définies

**Comment by bablukid** [comment]
Ce cas est trop particulier pour être intégré dans la version standard de Cagette. 
Tu peux traiter ce cas via un plug-in Cagette éventuellement !
