### ISSUE TITLE
Installation 404

### ISSUE THREAD

**Issue by loconox** [bablukid/cagette#15]
Bonjour,

Je viens d'effectuer une nouvelle installation de cagette version neko en suivant la doc du wiki.
Je suis arrivé à la parti "Dernière étape", les tables se sont bien créés dans ma base, mais ensuite j'obtiens des erreurs 404. Sur l'index, je suis redirigé sur /user/login qui me renvoie une 404 et sur /install j'ai aussi une 404. Je n'ai pas d'erreur dans les log d'apache.

Merci d'avance de votre aide.

**Comment by bablukid** [comment]
ça doit surement venir du .htaccess qui n'est pas fonctionnel.

est ce qu'il existe bien à cet endroit : www/.htaccess ?

est ce que vous avez bien activé mod_rewrite en faisant "a2enmod rewrite" ?

**Comment by loconox** [comment]
Oui le module est bien activé et j'accède bien à index.n vu que j'ai une redirection vers /user/login.

**Comment by bablukid** [comment]
oui, visiblement tout fonctionne sauf le rewrite d'URL géré par le .htaccess
ce qui fait que toute autre URL que / ou /index.n ne fonctionne pas.

si mod_rewrite est bien activé et que .htaccess est bien placé et avec les bons droits, ça devrait marcher.

Est ce que dans le vhost, il y a bien "AllowOverride All" ?

**Comment by loconox** [comment]
Ah non effectivement, j'avais oublié cette directive, merci !
