### ISSUE TITLE
Recapitulatif par produit

### ISSUE THREAD

**Issue by orsonfrut** [bablukid/cagette#16]
Bonjour, 

Voici une erreur lorsque l'on demande le recap par produit dans la gestion de contrat:

Parse error: syntax error, unexpected '$ctx' (T_VARIABLE), expecting ')' in /home/amapomme/lang/fr/tmp/contractadmin__ordersByProduct.mtt.php on line 80

**Comment by bablukid** [comment]
C'est corrigé dans la version 0.9.1
