### ISSUE TITLE
Total par adhérent 

### ISSUE THREAD

**Issue by benchti** [bablukid/cagette#17]
Sur une commande **total par adhérent** https://app.cagette.net/contractAdmin/ordersByDate/2016-06-04 il manque le total pour le dernier? adhérent 
![cagette](https://cloud.githubusercontent.com/assets/663816/15412264/7fcd29d0-1e26-11e6-8737-a4fe4077e0ee.png)

**Comment by bablukid** [comment]
Bonjour, Merci pour le signalement de bug, c'est corrigé.
