### ISSUE TITLE
Documentation d'installation

### ISSUE THREAD

**Issue by arthurlutz** [bablukid/cagette#2]
Améliorer celle-ci.

Par exemple faire un lien dans http://aide.cagette.net/doku.php?id=installation_sur_votre_propre_serveur vers http://aide.cagette.net/doku.php?id=pour_les_developpeurs (où l'on peut trouver le code). Ou fournir un lien de téléchargement des deux dépots. 

Ensuite 

```
apt-get -uVf install apache2 mysql-server libapache2-mod-neko haxe
```

Et après, je sais pas... j'imagine qu'il faut compiler sugoi et cagette et copier des choses dans /var/www/ ? 

Avoir un INSTALL.md dans le dépot pour ceux qui passent pas par le wiki me semble utile aussi.

**Comment by bablukid** [comment]
Bonjour,
Je suis conscient qu'il manque beaucoup de doc à ce niveau là, le post sur le blog de Philippe Scoffoni m'a apporté une publicité innatendue dans la communauté open-source :) 

Je vais essayer de compléter la doc dans les jours qui viennent !  Je reposterai sur ce ticket dès qu'il y a du neuf.
a+ François

**Comment by bablukid** [comment]
Voici une doc d'installation pour Ubuntu : http://aide.cagette.net/doku.php?id=install_neko
Fais moi signe si tu rencontres des soucis.

**Comment by bablukid** [comment]
Bonjour, les doc d'install ont été mises à jour pour Neko et PHP (experimental)
http://www.cagette.net/wiki/dev:install
