### ISSUE TITLE
possibilité d'individualiser les dates de contrar par adhérent

### ISSUE THREAD

**Issue by akakeronos** [bablukid/cagette#22]
En tant que coordinateur, je veux mettre en place une individualisation des dates de début et de fin de contrat par adhérent au sein d'un même contrat afin de gérer un type de contrat flottant pour un an à date anniversaire.
Le coordinateur fixerait une date de début et de fin de contrat comme actuellement mais ensuite pour chaque adhérent au contrat il serait possible de surcharger la date de départ et de fin pour l'individualiser.
Une autre possibilité serait de déclarer une durée pour le contrat (1 an par exemple) ce qui permettrait en fonction de la date de départ choisit pour un adhérent de calculer automatiquement la date de fin.

critère d'acceptation : un nouveau type de contrat permet de définir pour chaque adhérent une date de fin individualisée. En complément, il me semble nécessaire de disposer d'une vue listant les adhérents d'un contrat avant même que ceux-ci aient effectués une commande. Cela permettrait d'introduire la notion d'engagement qui est formalisée dans le monde papier par la signature d'une contrat.
Une fois la date de départ sélectionnée, la date de fin est automatiquement calculée et l'adhérent est listé sur toutes les distributions du contrat correspondant à sa période de souscription. 
Bonus : le système prévient le coordinateur des adhérents dont l'échéance de renouvellement est proche.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/172413708080950/181595672444387)

**Comment by bablukid** [comment]
vu ensemble de vive voix.
