### ISSUE TITLE
gestion des adhésion

### ISSUE THREAD

**Issue by akakeronos** [bablukid/cagette#23]
En tant que coordinateur ou administrateur, je veux pouvoir créer un compte adhérent en lui affectant un mot de passe ou en lui envoyant un email lui demandant de se créer un mot de passe afin que l'adhérent sache qu'il a un compte mais pas encore de mot de passe.

critère d'acceptation : le formulaire de création de compte adhérent permet d'avertir l'adhérent que son compte a été créé et qu'il doit finaliser son inscription

**Comment by bablukid** [comment]
ça existe déjà ( dans la version actuelle, mais ça n'y etait pas dans la 0.9.1 ), tu peux créer un adhérent et ensuite il y a un bouton "envoyer une invitation"
