### ISSUE TITLE
install php et dernière étape /install

### ISSUE THREAD

**Issue by garwinch** [bablukid/cagette#25]
Problème lors de la dernière étape de l'install, pour crée l'utilisateur admin. 
La doc fait référence à un dossier /cagette/install qui de toute évidence doit exister dans la version neko (le wiki pointe vers la même page) mais qui est absent de l'archive pour php .. 

Impossible donc de créer un admin user alors que le reste est bien configurer.. un peut frustrant en fait. 

merci pour le reste

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/172413708080950/198477828716020)

**Comment by bablukid** [comment]
es tu sûr que le .htaccess est bien actif dans www ? ( et que mod_rewrite est bien activé sur apache ? )

**Comment by garwinch** [comment]
Bonjour, et merci de l’intérêt que tu porte à mon problème. En fait, j'utilise la distribution Yunohost pour l'auto-hébergement. le serveur web y est NGINX ... 

serait-ce la source de mon problème?

**Comment by bablukid** [comment]
oui ça vient de là, tout est prévu pour apache , pas pour nginx.  Ceci dit, il faudrait juste "traduire" le .htaccess (spécifique à Apache) pour Nginx.  Je ne maitrise pas le sujet, mais tu devrais trouver de la doc sur le web facilement, genre : https://winginx.com/en/htaccess

**Comment by garwinch** [comment]
Si je modifie le contenu du .htaccess pour ce qui suis, je suis redirigé vers la racine du server web mondomaine/blog une idée ? 

```
<FilesMatch "^([_a-z0-9A-Z-])+$">

        RewriteEngine On
        RewriteRule (.*)/css/[a-z0-9]+/(.*) /css/$2 [L]
        RewriteRule (.*)/js/[a-z0-9]+/(.*) /js/$2 [L]

        Rewrite (.*)/css/[a-z0-9]+/(.*) /css/$2 break;
        Rewrite (.*)/js/[a-z0-9]+/(.*) /js/$2 break;
        Rewrite ^(.*)$ /index.php;

        RewriteCond %{REQUEST_URI} !\.(png|gif|jpg|ico|swf|css|js|dat)$
        RewriteRule (.*) /index.php
</FilesMatch>
```

**Comment by bablukid** [comment]
Si tu utilises Nginx , cette syntaxe n'est pas adaptée. Le htaccess fourni avec Cagette est pour Apache.
Je n'ai pas de nginx sous la main pour pouvoir tester.

Le site https://winginx.com/en/htaccess propose cette traduction : 
# nginx configuration
location ~ \.(png|gif|jpg|ico|swf|css|js|dat)$ {
}
location / {
rewrite (.*)/css/[a-z0-9]+/(.*) /css/$2 break;
rewrite (.*)/js/[a-z0-9]+/(.*) /js/$2 break;
rewrite ^(.*)$ /index.n;
}

**Comment by garwinch** [comment]
merci

j'ai testé plein de façon d'ajouter ces lignes a /etc/nginx/conf.d/TONDOMAINE.d/my_webapp__3.conf

aucune ne fonction, je suis renvoyer actuellement à la la page https://garwinch.ddns.net/yunohost/sso/ evec le fichier suivant : 
location /cagette {
alias /var/www/my_webapp__3/www/;

    rewrite (.*)/css/[a-z0-9]+/(.*) /css/$2 break;
    rewrite (.*)/js/[a-z0-9]+/(.*) /js/$2 break;
    rewrite ^(.*)$ /index.php;

    # Default indexes and catch-all
    index index.html index.php;
    try_files $uri $uri/ /cagette/index.php?$args;

    # Prevent useless logs
    location = /cagette/favicon.ico {
    log_not_found off;
    access_log off;

    }
    location = /cagette/robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }
    # Deny access to hidden files and directories
    location ~ ^/cagette/(.+/|)\.(?!well-known\/) {
        deny all;
    }

    # Execute and serve PHP files
    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        fastcgi_pass unix:/var/run/php5-fpm-my_webapp__3.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param REMOTE_USER $remote_user;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param SCRIPT_FILENAME $request_filename;
    }

    # Include SSOWAT user panel.
    include conf.d/yunohost_panel.conf.inc;
}

**Comment by bablukid** [comment]
J'ai réussi à installer Yunohost dans une machine virtuelle ( ça fait un moment que je voulais essayer ) ... Comment as tu fait pour créer un espace pour Cagette ? il y a une commande yunohost pour ça ou ça se fait à la main ?

**Comment by maniackcrudelis** [comment]
Salut @bablukid, je suis l'affaire à distance.

Pour créer un espace pour Cagette, installe l'application Custom Webapp.
Ça te créera un contenant vide dans /var/www et une config nginx de base pour installer une app php simplement.
Tu n'auras plus qu'à installer ton app dans le dossier et affiner la config nginx dans /etc/nginx/conf.d/domain.tld.d/my_webapp.conf

**Comment by bablukid** [comment]
C'est bon j'ai trouvé, j'ai pu l'installer sur mon Yunohost.  En fait le problème vient du fait que Cagette.net a besoin de son domaine ou sous-domaine à lui pour bien fonctionner.

Voici la procédure d'install (un peu brute de décoffrage) http://www.cagette.net/wiki/dev:install_yunohost

**Comment by garwinch** [comment]
merci de vos contribution, mais j'utilise comme nom de domaine garwinch.ddns.net qui permet un dns dynamique gratos. mais qui ne permet pas semble-il les sous domaines ! :-( je vais tenter d'éberger donc un autre domaine.ddns.net 
Merci encore

**Comment by bablukid** [comment]
oui je pense que ça va marcher en créant par exemple cagettedegarwinch.ddns.net

**Comment by garwinch** [comment]
cela fonctionne bien à la racine d'un domaine dédié. Pour paquager l'app pour yunohost, il serait préférable que l'on puisse l'installer sous la forme mondommaine.net/cagette ! (plus pratique pour de l'autohébergement )
cela demanderait-il une refonte lourde de l'app ? 
merci encore pour ce superbe outil :-)

**Comment by bablukid** [comment]
ça serait possible de l'adapter, mais ça demande quand même un peu de boulot ... donc pourquoi pas un jour, mais là c'est pas ma priorité vu la todo list que j'ai déjà

**Comment by gouessej** [comment]
@garwinch Pouvoir installer Cagette sous la forme mondommaine.net/cagette n'est pas nécessaire pour l'auto-hébergement. Tu aurais très bien pu prendre un abonnement VPN comprenant une adresse IP statique (par exemple chez un membre de la FFDN) au lieu d'utiliser ddns.net et prendre un nom de domaine distinct pour Cagette. Après, c'est sûr que ta suggestion permettrait de moins casquer, je me vois mal acheter un nom de domaine par logiciel installé sur mon serveur.
