### ISSUE TITLE
Erreurs Invalid operation

### ISSUE THREAD

**Issue by loconox** [bablukid/cagette#26]
Bonjour,

J'utilise cagette depuis quelques temps et j'avais parfois quelques erreurs mais de façons assez rare. J'ai tenté une maj et j'ai maintenant beaucoup plus d'erreurs. Ce-joint le rapport d'erreur reçus pas mail.

https://paste.swordarmor.fr/puEH

Je n'y connais rien en Haxe mais beaucoup plus en PHP. Est-ce que je peux migrer facilement vers la version PHP ? Est-ce que les deux projets sont au même stade d'avancement ? Est-ce que les BDD sont compatibles ?
## Merci d'avance.

Jérémie

**Comment by bablukid** [comment]
Bonjour,

Comme indiqué là, il faut synchroniser le shéma de base de données en allant sur /db ( avec un user admin ).
Voir la doc ici : http://www.cagette.net/wiki/dev:update

Sinon, oui tu peux passer sur la version PHP qui peut utiliser la même BDD.

MAIS : actuellement l'archive Neko est plus en avance que celle PHP qui est toujours la 0.9.1.
Je te recommande d'attendre la sortie officielle de la v0.9.2 (décembre?).

Et si tu connais bien PHP tu pourras comprendre ce que fait le code, mais pas le modifier puisque le PHP est généré à partir du code Haxe.  Pour info, une target PHP7 est en préparation dans le compilateur Haxe, qui générera du PHP beaucoup plus moderne et propre.

**Comment by loconox** [comment]
Merci pour ta réponse. L'url /db ne semble pas fonctionner correctement car j'obtiens une 302 vers / et pas de bouton "synchroniser".

**Comment by bablukid** [comment]
il faut être connecté avec un user administrateur, le user id 1 par exemple.

**Comment by loconox** [comment]
Effectivement je n'étais pas avec le bon user. J'ai réussi à synchroniser la base.
Par contre, j'ai toujours des erreurs sur la page /amap
```
Description technique de l'erreur

Invalid field access : firstName

Stack (ADMIN|DEBUG)


Called from macros.mtt line 111
Called from amap/default.mtt line 22
Called from templo/Loader.hx line 209
Called from templo/Loader.hx line 77
Called from templo/Loader.hx line 80
Called from sugoi/BaseApp.hx line 91
Called from sugoi/BaseApp.hx line 237
Called from a C function
Called from App.hx line 40
Called from sugoi/BaseApp.hx line 343
Called from C:\HaxeToolkit\haxe\std/sys/db/Transaction.hx line 32
```

**Comment by bablukid** [comment]
ça , c'est simplement que le user responsable de groupe n'a pas de prénom , ce qui est obligatoire ( les fiches adhérent doivent au moins contenir prénom-nom-email )

Complète la fiche du user correspondant, et il n'y aura plus d'erreur (  si la page n'est pas accessible, passe par "/db" puis "User" )

**Comment by loconox** [comment]
C'est étonnant car tous les utilisateurs dans la base ont le champ firstName de renseigner.

Par contre, je ne sais pas si c'est lié, mais il y a un problème d'encodage des caractères accentués dans la base. A l'affichage du site,  je n'ai pas de problème, mais quand je consulte les données dans la base, ça ne s'affiche pas correctement. Je vais faire des tests pour voir.

**Comment by bablukid** [comment]
1/ ok c'est peut etre que le groupe sur lequel tu es connecté n'a pas de responsable.

2/ tout est encodé en utf8, effectivement ça peut apparaitre en ISO en fonction de comment tu consultes la base (phpmyadmin ne fait pas forcément la conversion). Dans tout les cas, ce n'est pas un bug, c'est le comportement normal.

**Comment by loconox** [comment]
J'ai réussi à corriger le problème d'accès à la page /amap en mettant mon userid dans le champ userid de la table Amap, qui était à NULL avant.

L'encodage des tables était en latin1, j'ai essayé de tout passer en utf8 mais même après cela mon logiciel (Sequel Pro Mac), n'affiche pas correctement les valeurs des champs. Enfin les données sont bien afficher dans le navigateur, donc ce n'est pas un problème.

Merci.

**Comment by bablukid** [comment]
Oui, il y a peut etre quelquechose à faire avec les "collations" mysql, mais je ne suis pas expert de ça.  Comme ça fonctionne bien sur Cagette.net je clos le ticket.
