### ISSUE TITLE
Installer un environnement de développement

### ISSUE THREAD

**Issue by Eric86140** [bablukid/cagette#28]
Avant le premier _haxelib install dbadmin_ il demande de faire un _haxelib setup_.
Une fois le _haxelib run templo_ exécuté, on est dans le répertoire /usr/bin. Un _make compile_ ne donne rien.
Si on rouvre un terminal depuis /vagrant/cagette
Et que l'on lance de _make compile_ , alors là il râle car il demande de faire un _haxelib install dbadmin_
Deux cas : 
- soit les compilations doivent être faîtes en mode root, ce qui parait extrêmement dangereux.
- soit cette partie de l'installation doit être faite en mode user et non pas en mode root

**Comment by Eric86140** [comment]
Ce qui semble être la liste des commandes pour une compilation sans problème est plutôt :
`haxelib setup`
`haxelib install dbadmin`
`haxelib install templo`
`haxelib git sugoi https://github.com/bablukid/sugoi.git`
`haxelib install hxevents`
`haxelib install thx.semver`
`haxelib install hscript`
`haxelib git ufront-mail https://github.com/bablukid/ufront-mail`
`sudo sh -c "cd /usr/bin;haxelib run templo"`
`make compile`
Dans ce cas on a bien une compilation qui fonctionne
On a bien l'erreur qui s'affiche la première fois lors de l'appel de [http://cagette](url)
Mais au deuxième appel on a l'erreur suivante :
`Error : load.c(181) : Module not found : /home/user/Documents/cagette/www/../lang/fr/tmp/error.mtt.n`

**Comment by bablukid** [comment]
Ok j'ai mis à jour la doc : http://www.cagette.net/wiki/dev:install_dev

Pour la dernière erreur , c'est un template qui n'a pas été compilé. Essaye de faire 
```
make templates
make compile
```

**Comment by Eric86140** [comment]
contrairement à la nouvelle documentation, je n'ai pas trouvé de `Makefile_template` dans le code source
j'ai du faire 
`sed -e "s|\*/\*/\*/\*.mtt||" -i~ Makefile`
avant
`make templates`

L'erreur suivante est lors de l'appel de `http://cagette`
Il commute automatiquement vers `http://cagette/user/login`
pour lequel il donne 
_The requested URL /user/login was not found on this server._
Dans le répertoire `lang/fr/tmp` , il y a bien un fichier `user__login.mtt.n`
Cela ressemble à un problème dans la configuration d'Apache

**Comment by bablukid** [comment]
J'ai oublié de préciser : pour avoir les dernières modifications il faut utiliser la branche de dev actuelle 0.9.2 : https://github.com/bablukid/cagette/tree/0.9.2   il y a bien le fichier Makefile_template dans cette branche.

si l'url "/user/login" ne fonctionne pas, c'est que la ré-écriture d'url n'est pas en place.
Est ce que mod_rewrite est bien activé dans apache ?
Est que le .htaccess dans www est correct ?

**Comment by Eric86140** [comment]
Hello
la version 0.9.2 (SHA c83836ac293c774393f86bb715994d3ff1613aea) a effectivement bien un Makefile_templates, mais il faut quand même appliquer `sed -e "s|\*/\*/\*/\*.mtt||" -i~ Makefile`
D'autres installations semblent manquer pour avoir un` make compile` correct :
 `
haxelib install thx.csv; 
haxelib install datetime; 
haxelib install react; 
`
J'échoue enfin sur 
`js/react/ComposerApp.hx:36: lines 36-61 : Invalid JSX: Unsupported escaped char '{'`
J'arrête là pour ce soir, et ja vais retourner sur la version précédente (SHA df661fa8fda991fb8c6f5d5837f21e359e8c9766)
pour me reconcentrer sur les problèmes de ré-écriture d'URL
`Module rewrite already enabled` et le .htaccess semble assez conséquent pour faire un rewrite, mais je dois l'analyser plus en détail

**Comment by bablukid** [comment]
Je ne connais pas bien sed, ça efface "*/*/*/*.mtt" dans le Makefile, c'est ça ?
Effectivement pour les libs, ce sont de nouvelles libs que j'ai ajoutées récement.

coté rewrite, il faut avoir 
```
<FilesMatch "^([_a-z0-9A-Z-])+$">
	RewriteEngine On
	RewriteRule (.*)/css/[a-z0-9]+/(.*) /css/$2 [L]
	RewriteRule (.*)/js/[a-z0-9]+/(.*) /js/$2 [L]

    RewriteCond %{REQUEST_URI} !\.(png|gif|jpg|ico|swf|css|js|dat)$
    RewriteRule (.*) /index.n
</FilesMatch>
```
dans le dossier www ( il faut utiliser impérativement apache et mod_rewrite ).
Attention, avec apache 2.4 il faut dire explicitement qu'on autorise des .htaccess à modifier les directives apache dans un dossier particulier ( dans la conf apache )  : 
```
<Directory /vagrant/>
      Options Indexes FollowSymLinks
      AllowOverride All
      Require all granted
</Directory>
```

**Comment by Eric86140** [comment]
sed , c'est bien cela. Rassurez vous, moi aussi je n'ai jamais aimé ce truc. Mais il m'a bien fallu passer par là pour donner une ligne de commande à exécuter
J'ai donc fait marche arrière pour repartir d'une version plus stable
Mon erreur de user/login était due au AllowOverride **All**
Maintenant l'erreur est dans `http://cagette/install/firstInstall` :
`INSERT INTO Place (name,amapId) VALUES ('Place du marché', 2) Field 'zipCode' doesn't have a default value`

**Comment by leclercj** [comment]
Bonjour,

J'ai rencontré également le pb de l'erreur SQL avec firstInstall. C'est la config MySQL à changer
Cf https://groups.google.com/forum/?hl=fr#!topic/cagette/Cxqf2b1AAVg

J'ai aussi été amené à supprimer */*/*/*.mtt dans le Makefile

Et j'ai aussi l'erreur  js/react/ComposerApp.hx:36: lines 36-61 : Invalid JSX: Unsupported escaped char '{'
avec les versions récentes de la branche 0.9.2.
Le commit le plus récent sur 0.9.2 qui fonctionne chez moi est celui du 5 sept
https://github.com/bablukid/cagette/commit/328e9ab21b1b4120a70b1b190bad2874b134e9ce

**Comment by Eric86140** [comment]
c'est tout bon ! pour SQL
Je n'ai plus qu'à m'aligner sur la version https://github.com/bablukid/cagette/commit/328e9ab21b1b4120a70b1b190bad2874b134e9ce
