### ISSUE TITLE
Compiler en PHP ?

### ISSUE THREAD

**Issue by raphaelh** [bablukid/cagette#3]
Bonjour, et merci pour cagette !

Une petite question : quelle est la commande pour compiler cagette en PHP ?

**Comment by bablukid** [comment]
Bonjour,
Pour l'instant seule la version neko est fonctionnelle. 
Une version PHP sera surement disponible dans les mois qui viennent, mais je ne peut pas dire quand précisement.
Je laisse ce ticket ouvert et je reposterai ici pour que tu sois au courant quand ça sera fait !

**Comment by raphaelh** [comment]
Merci pour ta réponse !

D'après ce que j'ai compris, le compilateur Haxe est censé traduire le code source vers la plateforme choisie, du coup qu'est ce qui empêche la version PHP ?

Est-ce que tu pourrais me dire quelle est la commande pour compiler cagette en PHP, même si c'est pas encore fonctionnel ?

**Comment by bablukid** [comment]
Oui, haxe est multiplateforme, mais il y a souvent plein de petits trucs à corriger quand on passe sur une nouvelle plateforme.  Là en l'occurence, il y a un souci avec le moteur de template qui génère un template avec une syntaxe php invalide.  Il faudra que je prenne du temps pour faire le tour de tout ces petits bug.

Dans tout les cas, si tu veux voir comment ça fonctionne, je viens de créer une branche php : https://github.com/bablukid/cagette/tree/php

si tu es sur windows, tu peux ouvrir le hxproj avec FlashDevelop
sinon faire un ``haxe cagette-php.hxml``
pour lancer une compilation en ligne de commande.
mais il faut que tu aie toutes les libs haxe installées.

Si ton objectif est de découvrir haxe avec PHP, partir du répo de cagette n'est pas une bonne idée car il y a deja pas mal de code.

**Comment by raphaelh** [comment]
Je viens aux nouvelles concernant la version PHP. J'avais essayé en novembre de compiler en PHP, mais sans succès.

Je pourrais contribuer une version anglaise si besoin !

**Comment by bablukid** [comment]
Bonjour,

Je viens de pusher une version sur la branche php qui fonctionne (mais pas testée de fond en comble) : https://github.com/bablukid/cagette/tree/php

je viens de publier une version compilée PHP sur http://www.cagette.net/cagette-php.tar

Ensuite tu peux suivre la procédure d'install :
http://www.cagette.net/wiki/dev:install_neko#installation_de_cagettenet

**Comment by bablukid** [comment]
Doc mise à jour : http://www.cagette.net/wiki/dev:install_php

**Comment by bablukid** [comment]
Cagette.net fonctionne bien en PHP depuis la version 0.9.1.
