### ISSUE TITLE
Problème d'install

### ISSUE THREAD

**Issue by fab13n** [bablukid/cagette#33]
Comme je te disais hier soir, j'ai un soucis avec l'install, haxelib ne semble pas fonctionner pour les projets git :

```
$ haxelib git ufront-mail https://github.com/bablukid/ufront-mail
Installing ufront-mail from https://github.com/bablukid/ufront-mail
Could not execute git, please make sure it is installed and available in your PATH.
Cloning into '/home/fabien/local/haxe/ufront-mail/git'...
remote: Counting objects: 219, done.
remote: Total 219 (delta 0), reused 0 (delta 0), pack-reused 219
Receiving objects: 100% (219/219), 33.98 KiB | 0 bytes/s, done.
Resolving deltas: 100% (96/96), done.
Checking connectivity... done.
Process creation failure : git
```

et dans '/home/fabien/local/haxe/ufront-mail/', j'ai un repertoire git mais pas de .current, ce qui plante le make.

(même problème avec sugoi)

Ubuntu 14.04, haxelib 3.0.0

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/172413708080950/224288589905229)

**Comment by bablukid** [comment]
c'est bizarre, je n'ai jamais eu ce souci .... 
Est ce que tu as bien fait un `haxelib setup` après install de haxe ?
je vois le message `Could not execute git, please make sure it is installed and available in your PATH.` qui laisse penser que git ne fonctionne pas correctement sur ta machine

**Comment by bablukid** [comment]
Bonjour, ce ticket étant sans activité depuis longtemps, je ferme...
