### ISSUE TITLE
import en masse sans email

### ISSUE THREAD

**Issue by datalocale** [bablukid/cagette#4]
Lorsque l'on essaye d'importer un fichier d'adhérent il faut absolument que chacun ait un email sinon il y a une erreur. Pourquoi pas même si c'est limitatif mais dans ce cas il faut le préciser et affichier une erreur plus compréhensible

Error : INSERT INTO Error (date,ip,userAgent,url,error,uid) VALUES ('2016-02-08 21:19:21', '0.0.0.0', 'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0', '/member/import/', 'Chaque personne doit avoir un email, sinon elle ne pourra pas se connecter. Céline Le Basque/ Dautri13 55 94 80 n\'en a pas.\n\nCalled from controller/Member.hx line 375\nCalled from a C function\nCalled from C:\\HaxeToolkit\\haxe\\std/haxe/web/Dispatch.hx line 132\nCalled from C:\\HaxeToolkit\\haxe\\std/haxe/web/Dispatch.hx line 131\nCalled from controller/Main.hx line 246\nCalled from a C function\nCalled from C:\\HaxeToolkit\\haxe\\std/haxe/web/Dispatch.hx line 132\nCalled from C:\\HaxeToolkit\\haxe\\std/haxe/web/Dispatch.hx line 131\nCalled from sugoi/BaseApp.hx line 185\nCalled from sugoi/BaseApp.hx line 179\nCalled from a C function\nCalled from App.hx line 35\nCalled from sugoi/BaseApp.hx line 316\nCalled from C:\\HaxeToolkit\\haxe\\std/sys/db/Transaction.hx line 32\n', 5) Unknown column 'userAgent' in 'field list'

Called from C:\HaxeToolkit\haxe\std/neko/_std/sys/db/Mysql.hx line 128
Called from C:\HaxeToolkit\haxe\std/neko/_std/sys/db/Mysql.hx line 133
Called from C:\HaxeToolkit\haxe\std/sys/db/Manager.hx line 441
Called from C:\HaxeToolkit\haxe\std/sys/db/Manager.hx line 199
Called from C:\HaxeToolkit\haxe\std/sys/db/Object.hx line 53
Called from sugoi/BaseApp.hx line 236
Called from sugoi/BaseApp.hx line 245

**Comment by bablukid** [comment]
Bonjour,

Vous êtes dans un cas, ou il y a eu une erreur (exception) et le système n'a pas pu enregistrer l'erreur. en effet dans le framework utilisé, les erreurs sont logués en base ce qui est bien pratique.

L'erreur initiale est bien qu'il manque l'email d'une personne dans le fichier d'import.

Visiblement votre shéma de base de données n'est pas à jour, j'imagine que vous avez téléchargé une version récente de Cagette par dessus une version plus ancienne.

Avec votre compte admin, allez sur http://monUrl.fr/db et appuyez sur "synchronize database", le shéma de base sera mis à jour et ça réglera le problème.

Il manque dans Cagette une gestion d'update quand on passe à une version plus récente afin d'appliquer automatiquement des migrations sur la base, c'est dans ma todo list !

**Comment by bablukid** [comment]
Il est recommandé d'appliquer cette requete SQL aussi, car j'ai ajouté un champs "active" sur les produits.
`update Product set active=1`

**Comment by akakeronos** [comment]
Bonjour François,

Je ne vois pas de bouton synchronise database à l'url indiquée

**Comment by bablukid** [comment]
Tu devrais avoir un ecran de ce type : 
![image](https://cloud.githubusercontent.com/assets/758807/12911645/3bfb5a8a-cf14-11e5-8ad2-dc23fe87f4d7.png)

**Comment by akakeronos** [comment]
![capture](https://cloud.githubusercontent.com/assets/10322028/12911961/0d8bbb0c-cf16-11e5-89f0-46f476ac7d55.PNG)
![capture2](https://cloud.githubusercontent.com/assets/10322028/12911975/1ec9dcc8-cf16-11e5-9905-ae6415b6ea30.PNG)

**Comment by bablukid** [comment]
Ok visiblement le champs a bien été ajouté dans la table erreur, tu auras des messages d'erreur plus clairs maintenant :)

Sinon oui, il faut un email pour chaque adhérent pour que l'import fonctionne. on peut toujours tricher et ajouter un mail bidon si nécéssaire
