### ISSUE TITLE
modification du total d'une commande suite à la modification d'un prix unitaire

### ISSUE THREAD

**Issue by akakeronos** [bablukid/cagette#44]
Un adhérent a effectué une commande à partir de la liste des produits disponibles avec les prix affichés. Un mois plus tard un coordinateur change le prix unitaire d'un produit pour ouvrir une nouvelle commande. Les montants des anciennes commandes passées sont impactés par cette modification. C'est très gênant pour la comptabilité annuelle des adhérents et des producteurs.

**Comment by bablukid** [comment]
oui , c'est une incohérence qui a été corrigée dans la 0.9.2

**Comment by akakeronos** [comment]
ah cool. Et on peut l'installer cette version ?

**Comment by bablukid** [comment]
la version finale n'est pas prête, mais si tu peux passer à la ruche un de ces jours, je pourrai te la transmettre et t'aider à l'installer
