### ISSUE TITLE
column 'organic' not created in DB

### ISSUE THREAD

**Issue by fab13n** [bablukid/cagette#45]
the column 'organic' is missing in MySQL.
Installed from  wget http://www.cagette.net/cagette.tar on 2017-01-01, then replaced sources with git commit 4feadd756bac77bef59da8be24310453cd31c2a0

**Comment by bablukid** [comment]
did you check the "/db" url ? there is a "synchronize" button to update the DB schema  
http://www.cagette.net/wiki/dev:update

**Comment by fab13n** [comment]
I fixed it for myself directly in SQL. However, I believe either the installation process, or the instructions need to be updated, so that one starts in a consistent state. I guess most newcomers arrive with little or no experience with the Haxe framework :-)

**Comment by bablukid** [comment]
I started to write documentation about "Sugoï" which is the haxe web framework I'm using.
It is still very lightweight, but feel free to ask on a particular subject and I'll update the doc
http://sugoi.bubar.info
