### ISSUE TITLE
Pb Installation version dev 

### ISSUE THREAD

**Issue by Iledher** [bablukid/cagette#46]
Salut, 

j'essaye d'installer la version de dev de cagette mais je butte à l'étape de compilation : 
Voici la sortie de make template : 
```
(cd lang/fr/tpl; temploc2 -macros macros.mtt -output ../tmp/ *.mtt */*.mtt */*/*.mtt */*/*/*.mtt)
File not found */*/*/*.mtt
Makefile:8: recipe for target 'templates' failed
make: *** [templates] Error 255
```
Bref, j'ai besoin d'éclairage ! ;-)

Merci,
Mika

**Comment by bablukid** [comment]
effacez */*/*/*.mtt et ça va fonctionner

**Comment by Iledher** [comment]
OK, j'ai essayé mais ça ne passe toujours pas : 
```
(cd lang/fr/tpl; temploc2 -macros macros.mtt -output ../tmp/ *.mtt */*.mtt */*/*.mtt)
Called from templo/Main.nml line 183
Called from List.nml line 64
Called from a C function
Called from templo/Neko.nml line 467
Called from IO.nml line 100
Exception : (file_open, ../tmp/macros.mtt.n)
Makefile:8: recipe for target 'templates' failed
make: *** [templates] Error 255
```
Merci de votre aide !

**Comment by bablukid** [comment]
Visiblement il n'arrive pas à créer ../tmp/macros.mtt.n ... 

Est ce que ce répertoire existe bien ? est il accessible en écriture ?

**Comment by Iledher** [comment]
Le répertoire lang/fr/tmp/ n'existait pas, je l'ai créé et ça passe.

Merci ! 
Je continue...
