### ISSUE TITLE
problème d'installation chez OVH

### ISSUE THREAD

**Issue by yanrobil** [bablukid/cagette#50]
Bonjour,
après de nombreux tests d'installation sur mon hébergement OVH , j'ai toujours le message suivant en erreur
`Error : Temploc compilation of error.mtt failed : sh: temploc2: command not found

uncaught exception: There is no active transaction

in file: /home/totemium/www/cagette/lib/php/db/_PDO/PDOConnection.class.php line 96
#0 /home/totemium/www/cagette/lib/php/db/_PDO/PDOConnection.class.php(96): PDO->commit()
#1 /home/totemium/www/cagette/lib/sys/db/Transaction.class.php(36): php_db__PDO_PDOConnection->commit()
#2 /home/totemium/www/cagette/lib/sugoi/BaseApp.class.php(388): sys_db_Transaction::main(Object(php_db__PDO_PDOConnection), Array, Array)
#3 /home/totemium/www/cagette/lib/sugoi/BaseApp.class.php(418): sugoi_BaseApp->run()
#4 /home/totemium/www/cagette/lib/App.class.php(66): sugoi_BaseApp::main()
#5 /home/totemium/www/cagette/index.php(9): App::main()
#6 {main}`

Pouvez-vous me donner des pistes pour terminer l'installation ?
Merci.

**Comment by bablukid** [comment]
vous etes en mode développement, il faut mettre debug à 0 dans config.xml

**Comment by yanrobil** [comment]
Mais bien sur !!!
Un grand merci. Tout fonctionne.
