### ISSUE TITLE
erreurs de compilation Haxe de cagette 

### ISSUE THREAD

**Issue by ocivelo** [bablukid/cagette#53]
bonjour, je m'appelle Christophe, 
je cherche à installer une version de développement pour l'association http://www.delafermeauquartier.org
car je veux modifier son fonctionnement pour un usage avec plusieurs maraichers qui livrent alternativement les lieux de distribution .
Je ne connais pas le langage haxe ;  j'ai suivi la procédure d'installation au plus près.
cependant à la compilation j'obtiens des erreurs  : 

j'ai essayé de rechercher la première erreur : src/controller/Transaction.hx:185: characters 11-14 : Type not found : pro.payment.LWCPayment
cependant, var lw = pro.payment.LWCPayment.getConnector(app.user.amap);   est bien reconnu par VisualStudioCode.  

D'avance merci,
Christophe Collard
mailto:chcollard@wanadoo.fr
P.S. 
 à la compilation j'obtiens les messages suivants : 

faq-A9-MINT cagette # sudo sh -c "cd /usr/bin;haxelib run templo"
temploc2 is now available in the current directory
faq-A9-MINT cagette # cp Makefile_template Makefile
faq-A9-MINT cagette # make templates
(cd lang/fr/tpl; temploc2 -macros macros.mtt -output ../tmp/ *.mtt */*.mtt */*/*.mtt)
faq-A9-MINT cagette # make compile
haxe cagette.hxml
Error: Error: Library smtpmailer is not installed : run 'haxelib install smtpmailer'
Makefile:5: recipe for target 'compile' failed
make: *** [compile] Error 1
faq-A9-MINT cagette # haxelib install smtpmailer
Downloading smtpmailer-0,0,1.zip...
Download complete : 14652 bytes in 0.2s (65.4KB/s)
Installing smtpmailer...
  Current version is now 0.0.1
Done
Installing dependency asys 0.2.0
Downloading asys-0,2,0.zip...
Download complete : 11089 bytes in 0.1s (100KB/s)
Installing asys...
  Current version is now 0.2.0
Done
Installing dependency tink_core 1.9.1
You already have tink_core version 1.9.1 installed
Installing dependency tink_io 0.5.0
Downloading tink_io-0,5,0.zip...
Download complete : 71524 bytes in 0.1s (507.1KB/s)
Installing tink_io...
  Current version is now 0.5.0
Done
Installing dependency tink_core 1.9.1
You already have tink_core version 1.9.1 installed
Installing dependency tink_streams 0.2.1
Downloading tink_streams-0,2,1.zip...
Download complete : 22891 bytes in 0.1s (223.1KB/s)
Installing tink_streams...
  Current version is now 0.2.1
Done
Installing dependency tink_core 1.9.1
You already have tink_core version 1.9.1 installed
Installing dependency tink_macro 0.13.3
Downloading tink_macro-0,13,3.zip...
Download complete : 79245 bytes in 0.1s (549.8KB/s)
Installing tink_macro...
  Current version is now 0.13.3
Done
Installing dependency tink_core 1.9.1
You already have tink_core version 1.9.1 installed
Installing dependency tink_streams 0.2.1
You already have tink_streams version 0.2.1 installed
Installing dependency mime 0.0.1
Downloading mime-0,0,1.zip...
Download complete : 19887 bytes in 0.1s (135.8KB/s)
Installing mime...
  Current version is now 0.0.1
Done
Installing dependency tink_await 0.1.7
Downloading tink_await-0,1,7.zip...
Download complete : 10045 bytes in 0.1s (91.3KB/s)
Installing tink_await...
  Current version is now 0.1.7
Done
Installing dependency tink_core 1.9.1
You already have tink_core version 1.9.1 installed
Installing dependency tink_macro 0.13.3
You already have tink_macro version 0.13.3 installed
Installing dependency tink_syntaxhub 0.3.6
Downloading tink_syntaxhub-0,3,6.zip...
Download complete : 19137 bytes in 0.1s (100.6KB/s)
Installing tink_syntaxhub...
  Current version is now 0.3.6
Done
Installing dependency tink_macro 0.13.3
You already have tink_macro version 0.13.3 installed
Installing dependency tink_priority 0.1.3
Downloading tink_priority-0,1,3.zip...
Download complete : 11284 bytes in 0.1s (102.2KB/s)
Installing tink_priority...
  Current version is now 0.1.3
Done
faq-A9-MINT cagette # make compile
haxe cagette.hxml
src/db/User.hx:53: characters 11-30 : Warning : This class will be removed soon, please install the record-macros library
src/db/User.hx:54: characters 10-29 : Warning : This class will be removed soon, please install the record-macros library
src/controller/Transaction.hx:185: characters 11-14 : Type not found : pro.payment.LWCPayment
src/controller/Distribution.hx:39: characters 4-50 : Object requires field key
src/controller/Distribution.hx:39: characters 4-50 : For optional function argument 'data'
src/controller/Distribution.hx:45: characters 4-30 : Object requires field key
src/controller/Distribution.hx:45: characters 4-30 : For optional function argument 'data'
src/form/ColorRadioGroup.hx:17: characters 21-25 : Array<{ value : String, label : String }> should be Null<Array<{ value : String, key : String }>>
src/form/ColorRadioGroup.hx:17: characters 21-25 : Array<{ value : String, label : String }> should be Array<{ value : String, key : String }>
src/form/ColorRadioGroup.hx:17: characters 21-25 : Type parameters are invariant
src/form/ColorRadioGroup.hx:17: characters 21-25 : { value : String, label : String } should be { value : String, key : String }
src/form/ColorRadioGroup.hx:17: characters 21-25 : { value : String, key : String } has no field label
src/form/ColorRadioGroup.hx:17: characters 21-25 : For optional function argument 'data'
src/form/ColorRadioGroup.hx:8: lines 8-18 : Missing super constructor call
src/form/ColorRadioGroup.hx:31: characters 81-90 : { value : String, key : String } has no field label
src/form/ColorRadioGroup.hx:31: characters 102-111 : { value : String, key : String } has no field label
/root/haxelib/sugoi/git/src/sugoi/tools/DebugConnection.hx:112: lines 112-114 : Field addValue has different type than in sys.db.Connection
/usr/share/haxe/std/sys/db/Connection.hx:30: characters 1-56 : Interface field is defined here
/root/haxelib/sugoi/git/src/sugoi/tools/DebugConnection.hx:112: lines 112-114 : s : StringBuf -> v : Unknown<0> -> Void should be s : StringBuf -> v : Dynamic -> Void
/root/haxelib/sugoi/git/src/sugoi/tools/DebugConnection.hx:112: lines 112-114 : Unknown<0> should be Dynamic
Makefile:5: recipe for target 'compile' failed
make: *** [compile] Error 1
faq-A9-MINT cagette # haxelib install record-macros
Downloading record-macros-1,0,0-alpha.zip...
Download complete : 31860 bytes in 0.1s (199.9KB/s)
Installing record-macros...
  Current version is now 1.0.0-alpha
Done
faq-A9-MINT cagette # make compile
haxe cagette.hxml
src/db/User.hx:53: characters 11-30 : Warning : This class will be removed soon, please install the record-macros library
src/db/User.hx:54: characters 10-29 : Warning : This class will be removed soon, please install the record-macros library
src/controller/Transaction.hx:185: characters 11-14 : Type not found : pro.payment.LWCPayment
src/controller/Distribution.hx:39: characters 4-50 : Object requires field key
src/controller/Distribution.hx:39: characters 4-50 : For optional function argument 'data'
src/controller/Distribution.hx:45: characters 4-30 : Object requires field key
src/controller/Distribution.hx:45: characters 4-30 : For optional function argument 'data'
src/form/ColorRadioGroup.hx:17: characters 21-25 : Array<{ value : String, label : String }> should be Null<Array<{ value : String, key : String }>>
src/form/ColorRadioGroup.hx:17: characters 21-25 : Array<{ value : String, label : String }> should be Array<{ value : String, key : String }>
src/form/ColorRadioGroup.hx:17: characters 21-25 : Type parameters are invariant
src/form/ColorRadioGroup.hx:17: characters 21-25 : { value : String, label : String } should be { value : String, key : String }
src/form/ColorRadioGroup.hx:17: characters 21-25 : { value : String, key : String } has no field label
src/form/ColorRadioGroup.hx:17: characters 21-25 : For optional function argument 'data'
src/form/ColorRadioGroup.hx:8: lines 8-18 : Missing super constructor call
src/form/ColorRadioGroup.hx:31: characters 81-90 : { value : String, key : String } has no field label
src/form/ColorRadioGroup.hx:31: characters 102-111 : { value : String, key : String } has no field label
/root/haxelib/sugoi/git/src/sugoi/tools/DebugConnection.hx:112: lines 112-114 : Field addValue has different type than in sys.db.Connection
/usr/share/haxe/std/sys/db/Connection.hx:30: characters 1-56 : Interface field is defined here
/root/haxelib/sugoi/git/src/sugoi/tools/DebugConnection.hx:112: lines 112-114 : s : StringBuf -> v : Unknown<0> -> Void should be s : StringBuf -> v : Dynamic -> Void
/root/haxelib/sugoi/git/src/sugoi/tools/DebugConnection.hx:112: lines 112-114 : Unknown<0> should be Dynamic
Makefile:5: recipe for target 'compile' failed
make: *** [compile] Error 1

**Comment by bablukid** [comment]
Bonjour,
A priori, pas besoin de modifier cagette pour faire des livraisons alternatives. Chaque producteur a son contrat, et il suffit de bien programmer les livraisons pour qu'elles s'alternent. ( si j'ai bien compris ).

Coté problèmes de compilation :
il faut utiliser haxe 3.2.1
avoir temploc dans son PATH ( le compilateur de templates )
Mettre à jour la lib sugoi 
tu peux commenter les quelques lignes de src/controller/Transaction.hx:185 c'est un test que j'ai commité par erreur.

Dis moi si tu as encore des erreurs après ça.
