### ISSUE TITLE
Unknown description 'longtext'

### ISSUE THREAD

**Issue by loconox** [bablukid/cagette#54]
Bonjour,

Lorsque je tente d'accéder à `/db` j'obtiens l'erreur suivante :
```
Amap 	
Error :
Unknown description 'longtext'
Stack :

Called from sys/db/TableInfos.hx line 505
Called from sys/db/Admin.hx line 946
Called from sys/db/Admin.hx line 149
Called from sys/db/Admin.hx line 1076
Called from sys/db/Admin.hx line 1122
```

**Comment by bablukid** [comment]
C'est un problème venant de dbadmin, ce type de champs d'une des tables n'est pas reconnu.
Tu as du modifier des champs à la main en dehors de dbadmin

**Comment by loconox** [comment]
C'est possible. Tu as une idée de quelle table, quel champ ?

**Comment by bablukid** [comment]
non, c'est forcément un champ que tu as ajouté ou modifié toi même.

En fait pour ajouter des champs à une table, il faut ajouter dans le code une propriété à un objet du package db , compiler, et ensuite aller dans /db    , et là tu pourras "synchroniser" la table avec ton modèle dans le code.

**Comment by loconox** [comment]
J'ai réussi à corriger mon problème. En fait tous les champs qui devaient être en type `mediumtext` étaient en `longtext`. Il ne me semble pas avoir jamais touché au schéma de bdd. Je suspecte un problème de migration ... bref corrigé.
