### ISSUE TITLE
Erreur site inaccessible

### ISSUE THREAD

**Issue by loconox** [bablukid/cagette#57]
Bonjour,

Cet après midi, sans explication, mon site cagette est inaccessible. L'erreur suivante c'est produite : 

```
Error : std@file_delete

Called from C:\HaxeToolkit\haxe\std/neko/_std/sys/FileSystem.hx line 86
Called from templo/Loader.hx line 105
Called from templo/Loader.hx line 68
Called from a C function
Called from templo/Loader.hx line 54
Called from sugoi/BaseApp.hx line 45
Called from sugoi/BaseApp.hx line 52
Called from sugoi/BaseApp.hx line 281
```
Une idée ?

J'ai tenté de ré-installé entièrement l'application mais rien n'y fait.

**Comment by loconox** [comment]
Après un test de la cron j'obtiens cette erreur : 
```
root@axis:/var/www/cagette/www# neko index.n cron/daily
<pre>Error : Temploc compilation of error.mtt failed : Command not found : temploc2


Called from templo/Loader.hx line 123
Called from templo/Loader.hx line 68
Called from a C function
Called from templo/Loader.hx line 54
Called from sugoi/BaseApp.hx line 45
Called from sugoi/BaseApp.hx line 52
Called from sugoi/BaseApp.hx line 281
```
J'ai du faire sauter un truc ...

**Comment by bablukid** [comment]
la premiere erreur est due à une suppression de fichier qui échoue ( probleme de droits ? ), la deuxième erreur vient du fait que tu es en mode debug , mets debug à 0 dans le config.xml

**Comment by loconox** [comment]
Merci j'ai effectivement pu régler mon problème.
Je suis assez déçus de l'application neko, qui fournis des erreurs très vagues. Impossible de tenter de corriger le problème si on n'a pas un minimum d'habitude de l'outil. Je pense passer sur la version php lorsqu'elle sera en version 9.2 ou même changer de solution.
