### ISSUE TITLE
problème de sauvegarde d'une commande si des produits manquent

### ISSUE THREAD

**Issue by akakeronos** [bablukid/cagette#58]
J'ai essayé de sauvegarder une commande dont certains produits ne sont plus disponibles parce que le coordinateur a indiqué que les stocks étaient à 0. La validation de la commande génère une erreur et la commande n'est pas sauvegardée
![pbcommandeincomplete](https://user-images.githubusercontent.com/10322028/30034115-86ba5cca-919f-11e7-8f67-2a2ae90c39e2.PNG)

**Comment by bablukid** [comment]
est ce que c'est bon maintenant ?
