### ISSUE TITLE
Échec de la compilation en local : File not found macros.mtt

### ISSUE THREAD

**Issue by Djiko** [bablukid/cagette#59]
Bonjour,

je tente de monter un environnement de dev en local en suivant la [doc](https://www.cagette.net/wiki/dev:install_dev) mais j'ai une erreur à la compilation

```
make templates
(cd lang/fr/tpl; temploc2 -macros macros.mtt -output ../tmp/ *.mtt */*.mtt */*/*.mtt)
File not found macros.mtt
Makefile:8 : la recette pour la cible « templates » a échouée
make: *** [templates] Erreur 255
```

Ne connaissant pas (encore) Haxe et tout son écosystème, I'm stuck :)

**Comment by bablukid** [comment]
Il faut enlever le "*/*/*.mtt"
c'est un niveau de profondeur de dossier que tu n'as pas si tu compiles
Cagette sans plugin.

Pour info, si tu veux compiler la dernière version du master , il faut
utiliser la branche i18n de la librairie sugoi ( Cagette est en cours de
traduction dans d'autres langues )



2017-09-24 18:49 GMT+02:00 Gilles Coulais <notifications@github.com>:
