### ISSUE TITLE
import en masse avec erreur dans l'email

### ISSUE THREAD

**Issue by akakeronos** [bablukid/cagette#6]
S'il y a une erreur dans l'email l'import est en erreur

**Comment by akakeronos** [comment]
`Error : INSERT INTO Error (date,ip,userAgent,url,error,uid) VALUES ('2016-02-08 22:04:06', '0.0.0.0', 'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0', '/member/import', 'Le mail \'frederiquegoussard@ora\' est invalide, merci de modifier votre fichier\n\nCalled from controller/Member.hx line 458\nCalled from a C function\nCalled from C:\\HaxeToolkit\\haxe\\std/haxe/web/Dispatch.hx line 132\nCalled from C:\\HaxeToolkit\\haxe\\std/haxe/web/Dispatch.hx line 131\nCalled from controller/Main.hx line 246\nCalled from a C function\nCalled from C:\\HaxeToolkit\\haxe\\std/haxe/web/Dispatch.hx line 132\nCalled from C:\\HaxeToolkit\\haxe\\std/haxe/web/Dispatch.hx line 131\nCalled from sugoi/BaseApp.hx line 185\nCalled from sugoi/BaseApp.hx line 179\nCalled from a C function\nCalled from App.hx line 35\nCalled from sugoi/BaseApp.hx line 316\nCalled from C:\\HaxeToolkit\\haxe\\std/sys/db/Transaction.hx line 32\n', 5) Unknown column 'userAgent' in 'field list'

Called from C:\HaxeToolkit\haxe\std/neko/_std/sys/db/Mysql.hx line 128
Called from C:\HaxeToolkit\haxe\std/neko/_std/sys/db/Mysql.hx line 133
Called from C:\HaxeToolkit\haxe\std/sys/db/Manager.hx line 441
Called from C:\HaxeToolkit\haxe\std/sys/db/Manager.hx line 199
Called from C:\HaxeToolkit\haxe\std/sys/db/Object.hx line 53
Called from sugoi/BaseApp.hx line 236
Called from sugoi/BaseApp.hx line 245
`

**Comment by bablukid** [comment]
voir #4
