### ISSUE TITLE
Creation d'un nouvel export lors de la vue globale des commandes

### ISSUE THREAD

**Issue by Thothorg** [bablukid/cagette#60]
Bonjour,
J'utilise cagette sur un serveur propre et je cherche à obtenir un export sous la forme d'un tableau croisé :
              |client1 | client2 | client3 ...
porduit1 | nb
produit2 | nb
...
Pour me moment, j'ai fait un script python qui me permet de me connecter à ma base de donnée et qui m'exporte un tableau csv sous la forme présentée ci-dessus. [export_TCD.csv.zip](https://github.com/bablukid/cagette/files/1368412/export_TCD.csv.zip)
Cependant, il serait plus aisé si cette fonction pouvait être ajoutée directement sur le site. De plus, cela servirait peut être à d'autre personnes.
Je ne connais malheureusement pas du tout Haxe, et je ne peux donc pas proposer directement une pull request. 

Que puis je faire pour vous aider à mettre en place cette fonction ? 
Le script python contient déjà mes requêtes mysql nécessaires et je sais à peut prêt manier php si besoin.
Cordialement,

**Comment by Thothorg** [comment]
Bonjour,
L'ajout de cette fonctionnalité vous semble t'elle possible ?
Cordialement,

**Comment by bablukid** [comment]
Bonjour, 
merci pour votre proposition
malheureusement ma charge de travail actuelle ne me permet pas de traiter cette demande... 
François
