### ISSUE TITLE
compatibilité avec PostgreSQL

### ISSUE THREAD

**Issue by daftaupe** [bablukid/cagette#61]
Bonjour,

je n'ai trouvé qu'une mention dans la documentation d'installation pour installer cagette avec MySQL. Est-il prévu de le rendre compatible avec PostgreSQL ? Est-il même déjà possible de l'utiliser avec ?

Merci d'avance,
Cordialement,

**Comment by bablukid** [comment]
Non je ne pense pas, Cagette utilise beaucoup de fonctionnalités de MySQL ( moteur innoDb ) : système de transactions, de concurrence, clés étrangères ...etc      Et même si le SQL passait, je ne pense pas que neko ait des drivers pour postgre

**Comment by daftaupe** [comment]
Très bien, merci pour les informations @bablukid, je ferme donc ce ticket.
