### ISSUE TITLE
error : load.c(181) : Module not found : /vagrant/cagette/www/../lang/fr/tmp/error.mtt.n

### ISSUE THREAD

**Issue by antoinezulke** [bablukid/cagette#65]
Hello

Je suis en train d'installer un environnement de dev.
Je pense avoir bien suivi toutes les étapes indiquées.
Je suis sur ubuntu dans une machine virtuelle virtualbox.

Lorsque je lance la page cagette/install, j'ai le message d'erreur suivant:
rror : load.c(181) : Module not found : /vagrant/cagette/www/../lang/fr/tmp/error.mtt.n

Called from templo/Loader.hx line 132
Called from templo/Loader.hx line 135
Called from templo/Loader.hx line 70
Called from a C function
Called from templo/Loader.hx line 54
Called from sugoi/BaseApp.hx line 47
Called from sugoi/BaseApp.hx line 54
Called from sugoi/BaseApp.hx line 310

Effectivement le fichier "/vagrant/cagette/www/../lang/fr/tmp/error.mtt.n" n'existe pas.
Les étapes de compilation se passent bien, avec les commandes "haxe cagette.hxml, haxe cagetteJs.hxml et npm run build".
Y-a-t-il une étape que j'ai loupée qui permet de compiler les templates ?

Merci !!

Antoine

**Comment by bablukid** [comment]
Mets bien debug à 1 dans config.xml
créé le dossier lang/fr/tmp si il n'existe pas

**Comment by antoinezulke** [comment]
OK merci, c'est fait.

J'ai maintenant un message un peu différent : 
Error : Temploc compilation of error.mtt failed : Called from templo/Main.nml line 183
Called from List.nml line 64
Called from a C function
Called from templo/Neko.nml line 467
Called from IO.nml line 100
Exception : (file_open, /vagrant/cagette/www/../lang/master/tmp/macros.mtt.n)


Called from templo/Loader.hx line 123
Called from templo/Loader.hx line 68
Called from a C function
Called from templo/Loader.hx line 54
Called from sugoi/BaseApp.hx line 47
Called from sugoi/BaseApp.hx line 54
Called from sugoi/BaseApp.hx line 310

**Comment by bablukid** [comment]
ah ça c'est surement un probleme de droits ...  normalement apache s'execute avec le user www-data il faut donc mettre www-data en propriétaire de tout les fichiers.

à la base du projet fait un `chown -R www-data.www-data ./`

**Comment by antoinezulke** [comment]
Fait. Le changement de propriétaire a bien fonctionné.
Par contre toujours la même erreur.

**Comment by bablukid** [comment]
bizarre, tente un changement de droits sur les fichiers `chmod -R 775 ./`

**Comment by antoinezulke** [comment]
Pas mieux :'(

**Comment by bablukid** [comment]
tu as quoi si tu fais un `ls -lah`  dans /lang/master/ et dans /lang/master/tmp ?

**Comment by bablukid** [comment]
attention, il faut faire toutes ces opérations à l'insterieur de la VM ( en faisant `vagrant ssh` , si tu utilises vagrant )

**Comment by antoinezulke** [comment]
Suite à ton avant-dernière question j'ai vu que tmp n'existait pas dans master, je ne l'avais créé que dans fr..
Donc j'ai créé le répertoire, et ca y est je suis arrivé sur la page de login de cagette :-)
Merci beaucoup pour le coup de main!!
Je continue demain.

**Comment by bablukid** [comment]
ok, oui je me suis noté de commiter ces dossiers tmp sur GIT car le problème se pose souvent
