### ISSUE TITLE
Texte non traduit en français

### ISSUE THREAD

**Issue by antoinezulke** [bablukid/cagette#69]
Hello

Sur cagette.net, il reste quelques textes non traduits en français.
Ci-joint un exemple, sur la page Produit dans la gestion d'un contrat.

Cdt

Antoine
![cagette anglais](https://user-images.githubusercontent.com/32953659/33796681-d262c3c4-dcf9-11e7-9527-8ea5603d97ae.jpg)

**Comment by bablukid** [comment]
corrigé, merci
