### ISSUE TITLE
problème d'accès aux données de gestion des contrats

### ISSUE THREAD

**Issue by akakeronos** [bablukid/cagette#7]
Après avoir importé une centaine d'adhérent dans la base, je tente de revenir sur la partie contrat et je veux modifier 2 contrats qui pré-existaient.
Impossible de les gérer ou de les supprimer

`Error : INSERT INTO Error (date,ip,userAgent,url,error,uid) VALUES ('2016-02-08 22:23:20', '0.0.0.0', 'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0', '/contractAdmin/view/4', 'SELECT * FROM Product WHERE contractId = 4 AND active = TRUE Unknown column \'active\' in \'where clause\'\n\nCalled from C:\\HaxeToolkit\\haxe\\std/neko/_std/sys/db/Mysql.hx line 128\nCalled from C:\\HaxeToolkit\\haxe\\std/neko/_std/sys/db/Mysql.hx line 133\nCalled from C:\\HaxeToolkit\\haxe\\std/sys/db/Manager.hx line 441\nCalled from C:\\HaxeToolkit\\haxe\\std/sys/db/Manager.hx line 467\nCalled from db/Contract.hx line 146\nCalled from contractadmin/view.mtt line 58\nCalled from templo/Loader.hx line 209\nCalled from templo/Loader.hx line 77\nCalled from templo/Loader.hx line 80\nCalled from sugoi/BaseApp.hx line 90\nCalled from sugoi/BaseApp.hx line 218\nCalled from a C function\nCalled from App.hx line 35\nCalled from sugoi/BaseApp.hx line 316\nCalled from C:\\HaxeToolkit\\haxe\\std/sys/db/Transaction.hx line 32\n', 5) Unknown column 'userAgent' in 'field list'

Called from C:\HaxeToolkit\haxe\std/neko/_std/sys/db/Mysql.hx line 128
Called from C:\HaxeToolkit\haxe\std/neko/_std/sys/db/Mysql.hx line 133
Called from C:\HaxeToolkit\haxe\std/sys/db/Manager.hx line 441
Called from C:\HaxeToolkit\haxe\std/sys/db/Manager.hx line 199
Called from C:\HaxeToolkit\haxe\std/sys/db/Object.hx line 53
Called from sugoi/BaseApp.hx line 236
Called from sugoi/BaseApp.hx line 245
`

**Comment by bablukid** [comment]
Même souci que le #4 , le schéma de base n'est pas à jour. Tu peux faire la manip indiquée dans cette issue.
