### ISSUE TITLE
Modification des traductions

### ISSUE THREAD

**Issue by antoinezulke** [bablukid/cagette#70]
Bonjour,

Lorsque je modifie des traductions dans un fichier po, comment puis-je les prendre en compte ?

J'ai modifié le fichier /www/lang/texts_de.po, mais la modification n'est pas prise en compte.
J'ai tout recompilé, j'ai tenté "haxe templateGeneration.hxml",... il doit y voir une étape qui me manque.

Merci

Antoine

**Comment by bablukid** [comment]
il faut que debug soit à 1 pour que les traductions s'appliquent en live.

qqes infos dans la doc : https://www.cagette.net/wiki/dev:translation

**Comment by antoinezulke** [comment]
ok merci ca marche
