### ISSUE TITLE
Création auto des catégories - erreur SQL

### ISSUE THREAD

**Issue by antoinezulke** [bablukid/cagette#71]
Bonjour,

J'ai rencontré une nouvelle erreur MySQL de valeur par défaut manquante, en lancant la création automatique des catégories dans le groupe.

Cdt

Antoine

"Technical description of the error

INSERT INTO CategoryGroup (name,color,amapId) VALUES ('Produkteingenschaft', 2, 4) Field 'pinned' doesn't have a default value"

**Comment by bablukid** [comment]
corrigé, ne pas oublier de sync le shéma en allant sur /db avec un compte admin
