### ISSUE TITLE
Comment générer les fichiers Po

### ISSUE THREAD

**Issue by antoinezulke** [bablukid/cagette#72]
Bonjour

Après avoir bien lu https://www.cagette.net/wiki/dev:translation j'arrive maintenant à effectuer les traductions dans PoEdit, et les traductions sont bien prises en compte.
J'ai également rajouté plusieurs phrases à traduire dans les sources de Cagette.

Comment puis-je mettre à jour automatiquement le fichier Po pour qu'il contienne les nouvelles clefs en anglais que j'ai ajoutées dans les sources ?

Merci !

Antoine

**Comment by antoinezulke** [comment]
Je me suis dit que je pouvais peut-être générer le fichier Po avec la commande "sudo haxe potGeneration.hxml".
Mais j'obtiens l'erreur suivante : Error: Library cagette-hosted is not installed : run 'haxelib install cagette-hosted'
Et la commande "haxelib install cagette-hosted" me donne l'erreur "Error: No such Project : cagette-hosted"

**Comment by bablukid** [comment]
j'ai mis à jour la doc : https://www.cagette.net/wiki/dev:translation

et mis à jour également le fichier potGeneration.hxml

**Comment by antoinezulke** [comment]
Merci ! Tout fonctionne.
J'ai généré le allTexts, complété le po en francais, et fait un push.
On avance sur le po allemand.
