### ISSUE TITLE
Erreur de compilation - Cron.hx

### ISSUE THREAD

**Issue by antoinezulke** [bablukid/cagette#74]
Bonjour

Après avoir fait un pull sur bablukid/cagette, je ne peux plus compiler.
J'ai l'erreur suivante : /vagrant/cagette/libs/tink_await/0,3,0/src/tink/await/Await.hx:19: ok
src/controller/Cron.hx:240: characters 5-49 : Void should be sugoi.i18n.GetText

Ca concerne la ligne de code "this.t = sugoi.i18n.Locale.init(u.user.lang); //switch to the user language"

Une idée ?

Cdt

Antoine

**Comment by bablukid** [comment]
Je n'avais pas commité des modifs dans la lib sugoi,  je viens de les envoyer.

vas dans .haxelib/sugoi/git et fais un git pull

**Comment by antoinezulke** [comment]
Je suis un peu perdu... :)

Tu envoies ces modifs sur github bablukid/sugoi ? D'après ce que je vois sur GitHub la dernière modif date du 10 octobre.

Dans GitKraken je ne vois pas comment faire un pull spécifiquement sur un répertoire, et de toute facon le répertoire .haxelib n'est pas disponible sur bablukid/cagette...

J'ai bien trouvé le répertoire avec sugoi/git en local. De mémoire je l'ai installé en utilisant la commande haxelib. J'ai essayé un "haxelib update" et il m'a répondu que toutes les librairies sont à jour.

**Comment by antoinezulke** [comment]
J'ai résolu le problème. J'ai réussi à réinstaller les librairies.
