### ISSUE TITLE
App.hx - Traduction de getTranslationArray()

### ISSUE THREAD

**Issue by antoinezulke** [bablukid/cagette#75]
Bonjour

Il y a de nombreux textes non traduits qui se trouvent dans la fonction getTranslationArray() du fichier App.hx.

Je n'arrive pas à traduire cette fonction.

J'ai essayé le code suivant : 

"public static function getTranslationArray() {
		var t = sugoi.i18n.Locale.texts;
		var out = new Map<String,String>();
		out.set("firstName2", t._("Firstname of the partner"));
		out.set("lastName2", t._("Name of the partner"));
		out.set("email2", t._("E-mail of the partner"));"

Je n'ai pas d'erreur de compilation, mais j'obtiens l'erreur suivante lors du chargement de la page : 
"Uncaught exception - Invalid field access : get

Called from ? line 1
Called from App.hx line 27
Called from App.hx line 100"

Une idée ?

Merci

Antoine

**Comment by antoinezulke** [comment]
Bien évidemment avec des "_" après chaque "t.", ca ne fonctionne pas mieux.

**Comment by antoinezulke** [comment]
Bon aujourd'hui c'est encore un échec pour traduire cette fonction:
- soit j'essaye de le faire dans App.hx et je ne peux traduire que dans 1 seule langue. Je n'ai pas accès à app.session.lang.
- soit j'essaye de le faire dans la fonction function doEdit(c:db.Contract) de Contract.hx. Dans ce controlleur je connais la langue, mais la ligne de code App.t = sugoi.form.Form.translator = new sugoi.i18n.translator.TMap(out, "fr"); ne fonctionne pas à cet endroit là. J'obtiens l'erreur suivante : Technical description of the error

Invalid field access : _

Stack (ADMIN|DEBUG)


Called from sugoi/form/elements/Flags.hx line 150
Called from sugoi/form/FormElement.hx line 149
Called from sugoi/form/Form.hx line 568
Called from <header> line 1
Called from a C function
Called from form.mtt line 9
Called from templo/Loader.hx line 209
Called from form.mtt line 1
Called from templo/Loader.hx line 77
Called from templo/Loader.hx line 80
Called from sugoi/BaseApp.hx line 96
Called from sugoi/BaseApp.hx line 266
Called from a C function
Called from App.hx line 52
Called from sugoi/BaseApp.hx line 372
Called from sys/db/Transaction.hx line 32


Je réessaye un autre jour à tête reposée.

**Comment by bablukid** [comment]
laisse tomber ça va etre compliqué, il faudra que je me penche dessus...
