### ISSUE TITLE
Erreur de compilation

### ISSUE THREAD

**Issue by antoinezulke** [bablukid/cagette#78]
Depuis le dernier pull de ce soir, je ne peux plus compiler.
C'est visiblement du à la nouvelle ligne "<$Message message="${props.message}" />."
Une idée ?

Ci-dessous l'erreur de compilation :
/vagrant/GitHub/cagette/.haxelib/tink_await/0,3,0/src/tink/await/Await.hx:19: ok
js/react/LoginBox.hx:38: lines 38-66 : Unknown identifier : Message
js/react/LoginBox.hx:36: lines 36-67 : Field render overloads parent class with different or incomplete type
/vagrant/GitHub/cagette/.haxelib/react/1,3,0/src/lib/react/ReactComponent.hx:59: characters 1-32 : Base field is defined here
js/react/LoginBox.hx:21: lines 21-129 : Defined in this class
js/react/LoginBox.hx:36: lines 36-67 : Void -> Void should be Void -> react.ReactElement
js/react/LoginBox.hx:36: lines 36-67 : Void should be react.ReactElement
js/react/LoginBox.hx:36: lines 36-67 : Void should be { type : Dynamic, ?ref : Null<Dynamic>, props : Dynamic, ?key : Null<Dynamic> }

**Comment by bablukid** [comment]
j'avais oublié de commiter une nouvelle classe
