### ISSUE TITLE
imposible de charger une image

### ISSUE THREAD

**Issue by akakeronos** [bablukid/cagette#8]
Pour ajouter une image à un produit ou pour définir le logo de l'amap il y a une erreur

`
Erreur

Une erreur s'est produite lors de l'accès à la page demandée.

Si le site est indisponible, merci de revenir dans quelques minutes. En cas d'erreur répétées, merci de nous contacter de façon à ce que nous corrigions votre problème.
Description technique de l'erreur

[file_open,/var/www/cagette/www/../tmp/9f29450d2eb58feb555078bdefe28aa5]

Stack (ADMIN|DEBUG)

Called from C:\HaxeToolkit\haxe\std/neko/_std/sys/io/File.hx line 54
Called from sugoi/tools/UploadedImage.hx line 25
Called from controller/AmapAdmin.hx line 55
Called from a C function
Called from C:\HaxeToolkit\haxe\std/haxe/web/Dispatch.hx line 132
Called from C:\HaxeToolkit\haxe\std/haxe/web/Dispatch.hx line 131
Called from controller/Main.hx line 324
Called from a C function
Called from C:\HaxeToolkit\haxe\std/haxe/web/Dispatch.hx line 132
Called from C:\HaxeToolkit\haxe\std/haxe/web/Dispatch.hx line 131
Called from sugoi/BaseApp.hx line 185
Called from sugoi/BaseApp.hx line 179
Called from a C function
Called from App.hx line 35
Called from sugoi/BaseApp.hx line 316
Called from C:\HaxeToolkit\haxe\std/sys/db/Transaction.hx line 32`

**Comment by leclercj** [comment]
J'ai eu le même problème.
Le code suppose que le répertoire ../tmp existe, ce qui n'est pas le cas juste après l'install
Le contournement est de créer le répertoire ../tmp à la main la première fois (avec les bons droits)
Ensuite ça fonctionne

**Comment by akakeronos** [comment]
j'ai créé ce répertoire tmp avec 777 sur le user du serveur web et le problème persiste.

**Comment by bablukid** [comment]
Le message d'erreur est strictement identique ou différent ?

**Comment by akakeronos** [comment]
oui c'est le même message
