### ISSUE TITLE
à quoi correspond la liste "Le bureau..."

### ISSUE THREAD

**Issue by Djiko** [bablukid/cagette#80]
Hello,

il existe une liste de diffusion `Le bureau : les responsables + contrat + adhésions`. Qui est destinataire des mails envoyés sur cette liste ? Je n'ai rien trouvé dans la doc qui en parle (mais j'ai peut-être les yeux de travers :) )

Merci

**Comment by bablukid** [comment]
Cela correspond à tout ceux qui ont des droits particuliers dans le groupe
