### ISSUE TITLE
Impossible de supprimer un membre d'un groupe

### ISSUE THREAD

**Issue by Djiko** [bablukid/cagette#84]
Hello,

j'essaie de retirer un membre d'un groupe, ce qui n'a aucun effet. Ce membre a une commande annulée (commande passée puis remise à zéro, puisqu'il n'y a pas de possibilité de simplement supprimer cette commande). Cagette m'avertit que ce membre a une commande en cours et propose de supprimer le membre quand même. Le clic sur le bouton `effacer quand même` n'a pas d'effet : le membre reste actif dans le groupe.

**Commandes sur le profil membre**
![commande_en_cours](https://user-images.githubusercontent.com/789337/35040825-e8a5eaf6-fb82-11e7-96d3-6a409eb2b5d9.png)

**Commande annulée sur le contrat**
![commande_annulee](https://user-images.githubusercontent.com/789337/35040843-f38224da-fb82-11e7-9160-835682f2a72a.png)

Merci.

**Comment by bablukid** [comment]
ça devrait etre bon maintenant

**Comment by Djiko** [comment]
Je confirme :+1: 
Merci.
