### ISSUE TITLE
Error : Invalid field access : h

### ISSUE THREAD

**Issue by antoinezulke** [bablukid/cagette#86]
Hello

Il y a quelques jours j'ai obtenu l'erreur "Error : Invalid field access : h" pour toutes les pages de mon instance de cagette, sur mon environnement de développement en local.
L'erreur a disparu après une dizaine de minutes comme par magie.

Maintenant j'ai le même problème sur mon serveur de production, et il persiste.
J'ai pourtant exactement le même code sur l'environnement de développement et sur l'environnement de production.

Est-ce que quelqu'un a déjà rencontré ce problème ?

Ci-dessous le message d'erreur complet :

"Error : Invalid field access : h
Called from sugoi/BaseView.hx line 92
Called from design.mtt line 3
Called from templo/Loader.hx line 209
Called from design.mtt line 1
Called from templo/Loader.hx line 213
Called from error.mtt line 1
Called from templo/Loader.hx line 77
Called from templo/Loader.hx line 80
Called from sugoi/BaseApp.hx line 96
Called from sugoi/BaseApp.hx line 311"

Merci !

Antoine

**Comment by bablukid** [comment]
c'est une erreur de map vide ou un truc comme ça...

regarde ce qui est appelé à 
Called from sugoi/BaseView.hx line 92
et à
Called from design.mtt line 3

ça te mettra sur la voie...

**Comment by antoinezulke** [comment]
Oui bien sur j'ai regardé ca mais c'est vraiment étonnant car ce n'est que du code de base Sugoi et Cagette qui n'a pas été modifié.

design.mtt line 3   
          ::if getParam("__redirect")!=null::

sugoi/BaseView.hx line 92      
        function getParam( p : String ) {
		return App.current.params.get(p);
	}
                   
En plus ca fonctionne sur un environnement mais pas sur un autre...

**Comment by antoinezulke** [comment]
J'ai une bonne piste : lorsque je coupe le réseau de la virtualbox, j'obtiens la même erreur sur l'environnement de développement.

**Comment by bablukid** [comment]
je viens d'avoir la même erreur en installant cagette sur une nouvelle machine.

ça vient du fait que l'app s'init mal, car ça n'arrive pas à se connecter à la base de données.

vérifie la config de la BDD dans le config.xml

**Comment by antoinezulke** [comment]
Tu as vu juste je m'étais mélangé dans les fichiers de conf... :'(
Bizarre que ca fasse la même chose quand on coupe le réseau dans la machine virtuelle, mais ca n'empêche pas de travailler.

Merci !!!

**Comment by tekmans** [comment]
Salut j'ai eu le même soucis avec un caractère spécial dans le mot passe sql
Dans  le log apache j'ai eu plus d’info sur un problème de connexion sql ou j'ai vu que le mot de passe était pas pris en compte entièrement.
