### ISSUE TITLE
Traduction FR

### ISSUE THREAD

**Issue by trebmuh** [bablukid/cagette#88]
J'ai mis à jour la traduction française en utilisant weblate.
J'espère que c'est utile.

**Comment by trebmuh** [comment]
@bablukid : j'ai reçu un message (automatique) de weblate informant d'un possible conflit.

**Comment by bablukid** [comment]
Hello, merci pour ton aide.  ( et désolé pour ma réponse très très tardive )
En fait je ne sais pas vraiment me servir de Weblate.  
Effectivement entre temps beaucoup de commit ont été faits, et maitenant ça fait des conflits...   tu sais comment on peut régler ça ?

**Comment by trebmuh** [comment]
@bablukid non, aucune idée, navré.

**Comment by trebmuh** [comment]
@bablukid : tu as réussi a éviter les conflits?

**Comment by bablukid** [comment]
la bonne nouvelle c'est que j'ai réussi à corriger les conflits.
MAIS la mauvaise c'est que les conflits ne sont plus là parceque j'ai effacé toutes les contributions ... je n'ai eu aucun warning ...  je suis dégouté :-(

**Comment by trebmuh** [comment]
arf @bablukid : donc il faut que je les refasse ?

**Comment by trebmuh** [comment]
arf @bablukid
Je viens de traduire/valider chaînes de caractère. Pourrais-tu faire un test de merge, histoire que je puisse continuer les contributions en étant sûr qu'elles pourront être intégrées ?

**Comment by bablukid** [comment]
Non, désolé ça fait encore des conflits.
Je pense que je vais laisser tomber weblate, ça me parait inutilisable...  Si jamais tu connais des outils de traductions online performants, tiens moi au courant.

**Comment by trebmuh** [comment]
@bablukid : pourquoi ne pas utiliser simplement des pull request sur ce dépôt github ?

**Comment by bablukid** [comment]
non ça ne suffit pas, il faut que ça interagisse dans les 2 sens : weblate doit aussi etre capable de se mettre à jour depuis github pour connaitre les nouvelles chaines à traduire ( ou connaitre celles qui ont disparu ).

**Comment by trebmuh** [comment]
@bablukid : problème de compréhension, je reformule : pourquoi utiliser un outil de traduction en ligne ? Simplement utiliser des pull request github paraît suffisant.
