### ISSUE TITLE
envoi de mail "mot de passe oublié"

### ISSUE THREAD

**Issue by akakeronos** [bablukid/cagette#9]
Hello,

J'ai bien ajouté les paramètres d'envoi de mail dans le fichier de configuration et je peux vérifier que cela fonctionne dans l'onglet messagerie : je peux m'envoyer un mail test :)
En revanche lorsque j'appuie sur le bouton mot de passe oublié depuis la page de login je ne reçois rien. Une idée ?

Pascal

**Comment by bablukid** [comment]
Ah oui, je me suis rendu compte qu'il y avait un problème la dessus, qui a été réglé entre temps. Récupère la dernière version de cagette sur http://www.cagette.net/cagette.tar ( il faut juste ecraser ton install actuelle, c'est sans risques puisque l'archive ne contient pas de config.xml, ta conf sera donc préservée )
