### ISSUE TITLE
Optimiser l'impression des listes d'émargement

### ISSUE THREAD

**Issue by symac** [bablukid/cagette#90]
À l'heure actuelle, une liste pour les commandes de 53 amapiens génère un fichier de 8 pages. Pour chaque amapien, on a : 

- une ligne d'en-tête Qté / Ref / Produit ...
- une ligne avec la commande effective
- une ligne de total facturé

J'imagine qu'il y a des cas d'usage où le nombre de ligne peut être multiple et où c'est difficile de faire autrement, mais dans le cas classique d'une distribution où la seule différence serait le produit (panier / demi panier, on doit pouvoir optimiser les choses grandement) !

**Comment by bablukid** [comment]
as tu essayé les autres types de listes dans "vue globale des commandes" ?

**Comment by symac** [comment]
Tu parles d'une possibilité de modification au niveau des paramètres de l'appli ? Je ne vois rien qui ressemble à ça en tant qu'usager donc j'imagine que c'est lié à la configuration de mon groupe (Nansouty) sur laquelle je n'ai pas la main ? 

J'étais de distribution la semaine dernière, j'ai donc cliqué sur le lien qui apparaissait dans l'encart du jour et qui me disait d'imprimer la liste, c'est tout, je ne suis pas allé plus loin, et je n'ai pas de distrib programmé pour le moment donc je peux pas retester.

**Comment by bablukid** [comment]
ok effectivement il faut avoir des droits de coordinateur de groupe ou de contrat pour tester les différents types de rapports / listes.
