### ISSUE TITLE
Lien cassé  de téléchargement de la version PHP 

### ISSUE THREAD

**Issue by solidairnet** [bablukid/cagette#91]
Bonjour, le lien de téléchargement indiqué sur la page https://wiki.cagette.net/dev:install_php
renvoie une erreur 404 : http://www.cagette.net/cagette-php.tar
Est ce qu'on peut le télécharger ailleurs ?

Merci !

**Comment by bablukid** [comment]
Bonjour, il n'y a pas de version PHP récente à télécharger. ( je vais mettre à jour le wiki )

pour l'instant seule la version neko est maintenue, sinon vous avez toujours la possibilité de créer un groupe sur notre serveur www.cagette.net , c'est gratuit et sans limitations.
