### ISSUE TITLE
Struggling with install

### ISSUE THREAD

**Issue by Clem-D** [bablukid/cagette#92]
Hi, 
I'm trying to install "cagette" on my laptop. On my localhost, something very simple, I just want to try.

First I've followed this tutorial : https://wiki.cagette.net/dev:install_neko and I've noticed something weird : 
`<VirtualHost *:80>
  ServerName cagette
  DirectoryIndex index.n
  DocumentRoot /vagrant/cagette/www/
</VirtualHost>`

WTF is `index.n` ?

Ok so I was looking for a real index file and I was surprise I couldn't find any PHP or HTML files. I also though "_I've installed no dependencies, that's strange the tutorial doesn't talk about npm and stuff._"

So I kept searching and I found this page : https://wiki.cagette.net/dev:compile that could help a lot :)

But now I'm struggling with haxe : 

`haxe cagette.hxml` doesn't work, I've first got this error : 

>  Error: Error: Library sugoi is not installed : run 'haxelib install sugoi'

So I did `haxelib git sugoi git@github.com:bablukid/sugoi.git`

And I got 
>  Error: Error: Library templo is not installed : run 'haxelib install templo'

So I did `haxelib install templo`
And then I got 
> Error: Error: Library record-macros is not installed : run 'haxelib install record-macros'
So I did `haxelib install record-macros`

and now `haxe cagette.hxml` gives me :  
> Error: Error: Library record-macros version git is not installed

For information
 `haxe cagetteJs.hxml` gives me
> Error: Error: Library hxleaflet is not installed : run 'haxelib install hxleaflet'

and `haxelib install hxleaflet` gives me 
> Error: No such Project : hxleaflet

Well it's endless...
I don't know anything about haxe but please consider add a command like "npm run install:back" which install every haxe dependencies with good version etc. and then I think updating the wiki will be a good idea ;)

Thanks

EDIT : The link "http://www.cagette.net/cagette.tar" is not valid anymore but is still on the wiki.

**Comment by bablukid** [comment]
yes the install procedure needs some update.

since the .tar archive is not available anymore, you don't have the binaries so you need to compile the project from source.

the missing step is there https://wiki.cagette.net/dev:install_dev

this will install all haxe dependencies : 
```
haxelib setup
haxelib newrepo 
haxelib install cagette.hxml
haxelib install cagetteJs.hxml
```

**Comment by Clem-D** [comment]
Hi,
Thanks !
Actually it works even if commands create me a directory called "haxelib newrepo ?haxelib install cagette.hxml?haxelib install cagetteJs.hxml/" .
But still I don't know which file I'm supposed to give to "DirectoryIndex" config for apache.

**Comment by swergas** [comment]
I struggled too, but if you want to install it via docker, you can follow these steps that I used while working on #94 (and adapt things from the .travis.yml of this pull request, and from the dockerfile that somebody else has created if I remember correctly)

```
docker run -it ubuntu bash
apt-get -qq update
apt-get install -y curl imagemagick apache2 libapache2-mod-neko libmysqlclient-dev mysql-client mysql-server git software-properties-common npm wget
a2enmod neko
a2enmod rewrite
service apache2 restart
cd /root
git clone https://github.com/swergas/cagette.git # or bablukid/cagette.git once pull request #94 is merged
cd cagette
git checkout travis # or edit 000-default.conf by hand, or just stay on master once pull request #94 is merged
cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
service apache2 restart
service mysql start
mysql -e 'CREATE DATABASE cagette;'
cp config.xml.dist config.xml
add-apt-repository ppa:haxe/releases -y
apt-get update
apt-get install haxe -y
mkdir ~/haxelib && haxelib setup ~/haxelib
yes | haxelib install cagette.hxml
yes | haxelib install cagetteJs.hxml
ln -s /usr/bin/nodejs /usr/bin/node # otherwise npm install ends in error during installation of node-sass
npm install
haxe cagette.hxml
haxe cagetteJs.hxml
haxe templateGeneration.hxml
make -f Makefile_template templates LANG=fr
make -f Makefile_template templates LANG=de
make -f Makefile_template templates LANG=en
npm run build
echo "127.0.0.1 cagette" >> /etc/hosts
service networking restart
chown -R www-data:www-data /root
wget http://cagette -O- # on the first access it shows 'INSERT INTO Error', but this is normal
wget http://cagette -O- # from second access onwards, it works
```

**Comment by bablukid** [comment]
@Clem-D you need to compile the project to get the "index.n" in "www"
( haxe is a compiled langage like C# or Java, so you dont have an "index" file until you compiled the project )

"haxe cagette.hxml" will compile the backend in neko

"npm run build:js"  will compile the frontend in javascript

as explained here : http://wiki.cagette.net/dev:compile

**Comment by Clem-D** [comment]
Thanks but now i got the following error
> haxelib install cagetteJs.hxml/tink_await/0,3,0/src/tink/await/Await.hx:19: ok
src/App.hx:240: characters 9-46 : Class<sugoi.BaseController> has no field ControllerAction

doing "haxe cagette.hxml"

**Comment by bablukid** [comment]
ok, it's because of a recent update I made.
Please update Cagette ( `git pull origin master` ) and sugoi ( `cd .haxelib/sugoi/git && git pull origin i18n` )

**Comment by bablukid** [comment]
By the way , I just sent an updated archive of Cagette here : https://www.cagette.net/cagette.rar

So If you just want to try Cagette, it will be a lot simpler that trying to compile the whole project.

Another solution is also to create an account on www.cagette.net , it's free and unlimited

**Comment by Clem-D** [comment]
I guess you mean  https://www.cagette.net/cagette.tar

Thanks for the update.
I'm almost there (I hope) but after pulling and recompile surgoi when I got to http://cagette/ I get the following error : 

> 
> Error : load.c(181) : Module not found : /var/www/html/cagette/www/../lang/en/tmp/error.mtt.n
> 
> Called from templo/Loader.hx line 132
> Called from templo/Loader.hx line 135
> Called from templo/Loader.hx line 70
> Called from a C function
> Called from templo/Loader.hx line 54
> Called from sugoi/BaseApp.hx line 50
> Called from sugoi/BaseApp.hx line 57
> Called from sugoi/BaseApp.hx line 317
> 

I moved the main directory and I installed the tar file you posted and I restarted apache2. But now when I go to http://cagette/ it redirects me to http://cagette/user/login and I get a 404.

**Comment by bablukid** [comment]
pb 1 : Ok, you need to set debug="1" in config.xml

pb 2 : if you have a 404 , check that you have an .htaccess file in www  and that mod_rewrite is installed in apache2

**Comment by Clem-D** [comment]
pb 1 : 
I have this error 
```
Error : Temploc compilation of error.mtt failed : Command not found : temploc2


Called from templo/Loader.hx line 123
Called from templo/Loader.hx line 68
Called from a C function
Called from templo/Loader.hx line 54
Called from sugoi/BaseApp.hx line 50
Called from sugoi/BaseApp.hx line 57
Called from sugoi/BaseApp.hx line 317

```
And I get this from /var/log/apache2/error.log : 
```
[file_contents,/var/www/html/cagette/www//lang/texts_en.mo]\n\nCalled from /usr/share/haxe/std/neko/_std/sys/io/File.hx line 30\nCalled from /usr/share/haxe/std/neko/_std/sys/io/File.hx line 34\nCalled from sugoi/i18n/Locale.hx line 45\nCalled from sugoi/BaseApp.hx line 80\nCalled from sugoi/BaseApp.hx line 162\nCalled from sugoi/BaseApp.hx line 201\nCalled from a C function\nCalled from App.hx line 49\nCalled from sugoi/BaseApp.hx line 379\nCalled from sys/db/Transaction.hx line 32
```
pb 2 : 
```
$ sudo a2enmod rewrite
Module rewrite already enabled
```

And I got the following file (under cagette.tar folder) : 
./www/file/.htaccess
./www/.htaccess

**Comment by bablukid** [comment]
pb 1 : 
execute "haxelib run templo" and copy the generated "temploc2" command to /usr/bin
pb 1.2 : 
the file texts_en.mo should be in cagette.tar , in www/lang

p2 :
check that the webroot is the www of your cagette folder.
Check also that apache conf is ok , as explained in http://wiki.cagette.net/dev:install_neko

**Comment by Clem-D** [comment]
pb 1:
haxelib run templo
Error: Library templo version 3.0.0 does not have a run script

in www/lang I got only *po file : 
 allTexts.pot  texts_de.po  texts_en.po  texts_es.po  texts_fr.po

**Comment by bablukid** [comment]
no idea how to solve pb 1.

If you just want to run Cagette on your computer ,and you dont want to work on the code, I strongly recommand to downlad www.cagette.net/cagette.tar   which have all the po files, all the templates ready to use.
