### ISSUE TITLE
Champ password non accessible avec firefox

### ISSUE THREAD

**Issue by loconox** [bablukid/cagette#97]
Bonjour,

Je rencontre un souci avec la version sur master et le navigateur Firefox.
Sur la page de login, le champ password n'est pas sélectionnable, que ça soit avec TAB ou la souris, je ne parviens pas à renseigner le mot de passe dans le champ.

Firefox : 59.0.2
OS : ubuntu

**Comment by bablukid** [comment]
merci , ça me le fait aussi sur FF sur Ubuntu ...  bizarre que personne d'autre se soit plaint ...

**Comment by bablukid** [comment]
c'est une box faite en React Js.... si jamais tu vois d'ou ça vient ça m'aiderait car là je ne trouve pas pour l'instant

**Comment by bablukid** [comment]
ok on dirait que le paquet Firefox est bugué, il faut l'installer par snap...

https://support.mozilla.org/fr/questions/1214123

**Comment by loconox** [comment]
Salut,
J'ai testé en installant la version de Snap et ça n'a pas résolue mon problème. J'ai aussi testé avec le version beta, rien ne change. (60, 61 et 62).

**Comment by bablukid** [comment]
ah bizarre , tu as bien effacé l'ancienne version  ?
chez moi ça fonctionne ( FF 60 sur Ubuntu 16.04 )

**Comment by bablukid** [comment]
Bon ok, merci pour le suivi
