### ISSUE TITLE
Use input type number for orders

### ISSUE THREAD

**Issue by dedesite** [bablukid/cagette#98]
When you want to order something, input are currently of type `text`, it will be better if they were of type `number`.

Ideally, it would be best if it was some sort of "-/+" widget which update automatically the price of the order.

**Comment by bablukid** [comment]
Yes we know, our designer is working on a brand new shop interface ( which will be made with react js )... and we planned to user a +/- widget ;-)

**Comment by dedesite** [comment]
Ok, can we have some info about this new interface ? Where is the best place to submit new ideas ?

Anyway, cagette.net is really an awesome project and helped us a lot !

Thanks 
Andréas
